// Code generated by goyacc -l -o parse_yacc.go -v parse_yacc.states.txt parse_yacc.y. DO NOT EDIT.
package datetime

import __yyfmt__ "fmt"

type yySymType struct {
	yys            int
	DateTimeRanges *DateTimeRanges
	DateTimeRange  *DateTimeRange
	DateTime       *DateTime
	Date           *Date
	Time           *Time
	TimeZone       *TimeZone
	string         string
	strings        []string
}

const ILLEGAL = 57346
const A = 57347
const ADD = 57348
const AM = 57349
const AMP = 57350
const AND = 57351
const AT = 57352
const BEGINNING = 57353
const CALENDAR = 57354
const COLON = 57355
const COMMA = 57356
const DATE = 57357
const DATES = 57358
const DEC = 57359
const FROM = 57360
const GOOGLE = 57361
const ICS = 57362
const IN = 57363
const LPAREN = 57364
const NEXT = 57365
const OF = 57366
const ON = 57367
const ORD_IND = 57368
const PART = 57369
const P = 57370
const PM = 57371
const PERIOD = 57372
const QUO = 57373
const RPAREN = 57374
const SAVE = 57375
const SEMICOLON = 57376
const SUB = 57377
const THROUGH = 57378
const T = 57379
const TH = 57380
const THE = 57381
const THIS = 57382
const TILL = 57383
const TIME = 57384
const TO = 57385
const UNTIL = 57386
const WHEN = 57387
const Z = 57388
const IDENT = 57389
const INT = 57390
const MONTH_NAME = 57391
const TIME_NAME = 57392
const TIME_ZONE = 57393
const TIME_ZONE_ABBREV = 57394
const RELATIVE_DAY = 57395
const WEEKDAY_NAME = 57396
const WEEKDAY_SHORT_NAME = 57397
const YEAR = 57398

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ILLEGAL",
	"A",
	"ADD",
	"AM",
	"AMP",
	"AND",
	"AT",
	"BEGINNING",
	"CALENDAR",
	"COLON",
	"COMMA",
	"DATE",
	"DATES",
	"DEC",
	"FROM",
	"GOOGLE",
	"ICS",
	"IN",
	"LPAREN",
	"NEXT",
	"OF",
	"ON",
	"ORD_IND",
	"PART",
	"P",
	"PM",
	"PERIOD",
	"QUO",
	"RPAREN",
	"SAVE",
	"SEMICOLON",
	"SUB",
	"THROUGH",
	"T",
	"TH",
	"THE",
	"THIS",
	"TILL",
	"TIME",
	"TO",
	"UNTIL",
	"WHEN",
	"Z",
	"IDENT",
	"INT",
	"MONTH_NAME",
	"TIME_NAME",
	"TIME_ZONE",
	"TIME_ZONE_ABBREV",
	"RELATIVE_DAY",
	"WEEKDAY_NAME",
	"WEEKDAY_SHORT_NAME",
	"YEAR",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 4,
	25, 110,
	-2, 15,
	-1, 14,
	9, 189,
	17, 189,
	35, 189,
	36, 189,
	41, 189,
	43, 189,
	44, 189,
	48, 189,
	49, 189,
	-2, 210,
	-1, 15,
	15, 215,
	23, 215,
	38, 215,
	40, 215,
	42, 215,
	48, 215,
	49, 215,
	53, 215,
	54, 215,
	55, 215,
	56, 215,
	-2, 120,
	-1, 28,
	49, 182,
	56, 182,
	-2, 145,
	-1, 45,
	10, 222,
	18, 222,
	50, 222,
	-2, 164,
	-1, 46,
	10, 221,
	18, 221,
	50, 221,
	-2, 163,
	-1, 104,
	15, 208,
	23, 208,
	38, 208,
	40, 208,
	42, 208,
	48, 208,
	49, 208,
	53, 208,
	54, 208,
	55, 208,
	56, 208,
	-2, 120,
	-1, 105,
	15, 209,
	23, 209,
	38, 209,
	40, 209,
	42, 209,
	48, 209,
	49, 209,
	53, 209,
	54, 209,
	55, 209,
	56, 209,
	-2, 120,
	-1, 130,
	28, 128,
	51, 128,
	52, 128,
	-2, 93,
	-1, 136,
	17, 92,
	35, 92,
	36, 92,
	41, 92,
	43, 92,
	44, 92,
	48, 92,
	-2, 116,
	-1, 137,
	17, 93,
	35, 93,
	36, 93,
	41, 93,
	43, 93,
	44, 93,
	48, 93,
	-2, 118,
	-1, 167,
	6, 171,
	9, 171,
	14, 171,
	17, 171,
	30, 171,
	31, 171,
	48, 171,
	-2, 206,
	-1, 177,
	25, 110,
	-2, 17,
	-1, 184,
	17, 210,
	35, 210,
	36, 210,
	41, 210,
	43, 210,
	44, 210,
	-2, 189,
	-1, 207,
	15, 120,
	23, 120,
	38, 120,
	40, 120,
	42, 120,
	48, 120,
	49, 120,
	53, 120,
	54, 120,
	55, 120,
	56, 120,
	-2, 75,
	-1, 228,
	10, 88,
	18, 88,
	25, 88,
	42, 88,
	48, 88,
	50, 88,
	-2, 100,
	-1, 233,
	10, 208,
	18, 208,
	42, 208,
	48, 208,
	50, 208,
	56, 208,
	-2, 120,
	-1, 234,
	10, 209,
	18, 209,
	42, 209,
	48, 209,
	50, 209,
	56, 209,
	-2, 120,
	-1, 280,
	15, 125,
	23, 125,
	38, 125,
	40, 125,
	48, 125,
	49, 125,
	53, 125,
	54, 125,
	55, 125,
	56, 125,
	-2, 76,
	-1, 287,
	1, 120,
	9, 120,
	12, 120,
	13, 120,
	14, 120,
	17, 120,
	19, 120,
	20, 120,
	25, 120,
	31, 120,
	37, 120,
	-2, 213,
	-1, 288,
	1, 120,
	9, 120,
	12, 120,
	13, 120,
	14, 120,
	17, 120,
	19, 120,
	20, 120,
	25, 120,
	31, 120,
	37, 120,
	-2, 214,
	-1, 333,
	10, 213,
	18, 213,
	42, 213,
	48, 213,
	50, 213,
	56, 213,
	-2, 120,
	-1, 334,
	10, 214,
	18, 214,
	42, 214,
	48, 214,
	50, 214,
	56, 214,
	-2, 120,
}

const yyPrivate = 57344

const yyLast = 1064

var yyAct = [...]int16{
	129, 163, 62, 7, 238, 142, 8, 201, 119, 289,
	72, 242, 39, 73, 241, 40, 118, 164, 28, 20,
	133, 79, 4, 16, 106, 17, 105, 63, 114, 104,
	42, 11, 41, 19, 76, 19, 98, 29, 56, 189,
	51, 132, 39, 76, 75, 100, 38, 43, 94, 150,
	172, 171, 153, 159, 76, 76, 19, 161, 379, 365,
	76, 19, 39, 79, 155, 155, 364, 256, 126, 120,
	341, 337, 330, 218, 19, 125, 324, 85, 177, 96,
	305, 304, 127, 301, 128, 131, 299, 100, 252, 165,
	181, 176, 166, 122, 178, 125, 183, 204, 123, 124,
	168, 192, 76, 39, 244, 212, 213, 214, 250, 206,
	182, 198, 148, 169, 170, 191, 149, 174, 123, 124,
	207, 302, 209, 155, 146, 291, 115, 36, 208, 219,
	220, 37, 224, 228, 230, 240, 215, 251, 116, 39,
	94, 75, 190, 180, 235, 147, 234, 237, 249, 233,
	117, 202, 222, 151, 209, 223, 189, 231, 154, 143,
	221, 181, 243, 246, 9, 86, 366, 155, 96, 85,
	229, 74, 78, 44, 84, 93, 24, 57, 101, 340,
	247, 139, 58, 87, 88, 255, 216, 339, 140, 89,
	99, 90, 91, 306, 243, 53, 94, 239, 265, 172,
	253, 263, 52, 54, 246, 138, 254, 175, 270, 194,
	185, 152, 133, 135, 25, 261, 280, 281, 279, 39,
	101, 278, 18, 12, 162, 2, 288, 60, 71, 287,
	295, 70, 296, 282, 297, 298, 141, 78, 271, 84,
	290, 275, 107, 31, 193, 300, 195, 196, 197, 1,
	292, 145, 181, 59, 144, 26, 121, 200, 272, 217,
	13, 265, 155, 313, 309, 293, 61, 210, 283, 55,
	126, 120, 320, 5, 246, 3, 50, 125, 32, 308,
	285, 286, 248, 325, 127, 246, 315, 173, 328, 329,
	33, 331, 21, 0, 0, 122, 227, 312, 0, 0,
	123, 124, 0, 303, 0, 246, 319, 0, 0, 326,
	327, 334, 0, 336, 333, 0, 335, 343, 332, 0,
	229, 0, 271, 210, 349, 246, 245, 359, 360, 0,
	97, 342, 323, 361, 362, 363, 358, 347, 348, 357,
	81, 181, 0, 367, 353, 354, 355, 344, 181, 372,
	0, 258, 259, 260, 350, 0, 0, 0, 0, 264,
	266, 356, 108, 0, 109, 0, 273, 274, 368, 0,
	276, 103, 6, 0, 373, 6, 284, 6, 262, 77,
	80, 82, 92, 0, 0, 110, 111, 0, 0, 0,
	0, 398, 392, 0, 399, 383, 395, 396, 397, 0,
	387, 388, 389, 0, 390, 186, 0, 381, 393, 48,
	49, 47, 385, 0, 294, 0, 199, 0, 0, 40,
	391, 156, 264, 310, 394, 0, 0, 199, 0, 84,
	78, 0, 318, 0, 42, 321, 41, 0, 157, 0,
	307, 0, 0, 0, 0, 19, 187, 314, 274, 27,
	38, 43, 39, 165, 79, 44, 166, 0, 0, 199,
	0, 204, 199, 139, 168, 203, 205, 0, 338, 0,
	140, 0, 0, 86, 211, 0, 346, 169, 170, 0,
	0, 44, 351, 0, 48, 49, 47, 138, 86, 139,
	0, 87, 88, 184, 40, 135, 46, 89, 0, 90,
	91, 39, 0, 0, 76, 0, 87, 88, 0, 42,
	369, 41, 89, 45, 90, 91, 0, 375, 0, 152,
	19, 135, 0, 0, 27, 38, 43, 39, 64, 65,
	211, 0, 66, 371, 44, 382, 0, 0, 189, 376,
	377, 378, 139, 0, 0, 0, 67, 199, 0, 140,
	68, 0, 69, 0, 380, 0, 0, 257, 0, 384,
	0, 0, 0, 189, 0, 0, 138, 267, 268, 269,
	126, 120, 152, 0, 135, 44, 34, 125, 48, 49,
	47, 0, 203, 35, 127, 0, 0, 199, 40, 0,
	46, 44, 22, 0, 0, 122, 0, 317, 23, 139,
	123, 124, 0, 42, 0, 41, 140, 45, 0, 0,
	30, 0, 0, 14, 19, 15, 199, 199, 27, 38,
	43, 39, 0, 138, 0, 0, 0, 0, 0, 152,
	311, 135, 48, 49, 47, 316, 86, 0, 0, 0,
	165, 345, 40, 166, 156, 322, 0, 0, 204, 352,
	0, 168, 0, 0, 87, 88, 0, 42, 0, 41,
	89, 157, 90, 91, 169, 170, 0, 0, 19, 0,
	0, 0, 27, 38, 43, 39, 0, 370, 0, 0,
	57, 44, 34, 19, 48, 179, 47, 0, 0, 35,
	165, 0, 165, 166, 40, 166, 46, 0, 167, 0,
	204, 168, 0, 168, 0, 0, 0, 0, 0, 42,
	0, 41, 0, 45, 169, 170, 169, 170, 0, 14,
	19, 15, 0, 374, 27, 38, 43, 39, 44, 34,
	0, 48, 49, 47, 76, 0, 35, 0, 0, 0,
	0, 40, 0, 46, 0, 0, 0, 386, 0, 44,
	34, 0, 48, 49, 47, 0, 42, 35, 41, 0,
	45, 0, 40, 30, 46, 0, 14, 19, 15, 0,
	0, 27, 38, 43, 39, 0, 0, 42, 0, 41,
	95, 45, 0, 86, 0, 0, 0, 14, 19, 15,
	0, 0, 27, 38, 43, 39, 225, 226, 47, 0,
	66, 87, 88, 108, 0, 109, 40, 89, 156, 90,
	91, 112, 0, 0, 67, 0, 0, 0, 68, 0,
	69, 42, 0, 41, 0, 157, 110, 111, 236, 0,
	0, 0, 19, 0, 0, 0, 27, 38, 43, 39,
	44, 0, 0, 64, 65, 0, 165, 66, 139, 166,
	0, 126, 120, 0, 167, 140, 0, 168, 125, 0,
	0, 67, 0, 0, 0, 232, 0, 69, 0, 0,
	169, 170, 138, 0, 0, 160, 122, 0, 152, 0,
	135, 123, 124, 44, 0, 0, 64, 65, 0, 0,
	136, 139, 0, 0, 0, 0, 0, 0, 140, 0,
	0, 86, 0, 0, 67, 126, 120, 0, 137, 88,
	69, 0, 125, 0, 89, 138, 90, 91, 0, 130,
	88, 134, 0, 135, 108, 89, 109, 90, 91, 0,
	122, 0, 277, 0, 44, 123, 124, 64, 65, 0,
	0, 66, 139, 0, 0, 44, 0, 110, 111, 140,
	0, 0, 86, 139, 0, 67, 0, 0, 0, 68,
	140, 69, 0, 0, 0, 0, 138, 0, 0, 0,
	87, 88, 152, 0, 135, 0, 89, 138, 90, 91,
	0, 0, 0, 152, 44, 135, 188, 64, 65, 102,
	10, 66, 139, 10, 86, 10, 0, 0, 0, 140,
	0, 0, 83, 0, 0, 67, 0, 0, 0, 68,
	86, 69, 87, 88, 0, 0, 138, 158, 89, 0,
	90, 91, 134, 0, 135, 76, 19, 0, 87, 88,
	108, 0, 109, 0, 89, 0, 90, 91, 112, 115,
	0, 76, 19, 0, 0, 0, 0, 0, 0, 0,
	0, 116, 0, 110, 111, 113, 0, 0, 0, 0,
	0, 0, 0, 117,
}

var yyPact = [...]int16{
	565, 183, 168, 565, 515, 718, 6, 12, -16, 993,
	-14, 766, -1000, 739, 1025, 249, 884, 873, -1000, 145,
	110, -1000, 64, 77, -1000, 581, 396, 396, -1000, 840,
	-1000, -8, -1000, 80, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 194, -1000, -1000, -1000, -1000,
	183, -1000, -1000, -1000, -1000, 671, -1000, -1000, -1000, 183,
	-1000, 118, 515, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	168, -1000, 445, 201, 977, 142, 112, 163, -1000, -5,
	200, -5, -5, -5, -1000, 619, -1000, -1000, -1000, -1000,
	-1000, -1000, -5, 634, 25, 61, 471, -1000, 515, -1000,
	148, 148, -14, -44, 249, 249, 59, 112, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 148, 31,
	67, 67, -1000, -1000, -1000, -1000, -1000, -1000, 471, 783,
	-1000, 456, 47, 830, 798, -1000, -1000, -1000, 194, -1000,
	-1000, 145, -1000, -1000, -1000, -1000, -1000, -1000, 184, 119,
	-1000, -1000, 798, -1000, -1000, 684, -1000, -1000, -14, -1000,
	56, 686, 142, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 102, 40, -1000, -1000, 515, -1000, -1000,
	-8, -1000, 524, 148, 1025, -16, -5, -5, -5, -1000,
	-1000, 524, 148, -1000, -5, 7, -16, -16, -1000, -1000,
	83, -5, 686, -44, -1000, -5, 919, 249, 67, 974,
	634, -5, 148, 148, 798, -1000, 935, -1000, -1000, 93,
	-1000, -1000, 249, -1000, 783, -1000, -1000, -44, 148, 549,
	-1000, 249, -1000, 249, 249, 38, -1000, -1000, -1000, -1000,
	184, -1000, -1000, 35, 86, 447, -1000, -1000, -1000, -1000,
	33, 32, 180, -1000, 148, 581, 148, -5, 7, -44,
	515, 148, 581, -16, -5, 54, 148, -5, -44, 515,
	-5, 142, 447, -16, 447, 142, -1000, 28, -1000, -1000,
	31, -1000, 47, 686, -44, 935, 935, 249, 249, 24,
	249, -1000, -1000, 142, 581, -1000, -1000, -1000, -1000, 798,
	-1000, 798, 23, 686, 174, 166, 22, 581, 67, -44,
	148, -5, 142, 924, 581, 67, -44, -5, 148, 142,
	924, 581, 581, 83, 357, -1000, 249, 249, -1000, -1000,
	-1000, -1000, 249, 249, 249, -1000, -1000, -1000, -1000, 18,
	11, 153, 249, -1000, 524, -5, 148, 148, 249, -1000,
	524, -16, -5, 148, 148, 148, 142, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 10, -1000, 148, -44,
	-5, 581, -1000, 148, -44, -16, 581, 581, 581, -1000,
	581, 142, -44, 67, 581, 142, -44, 67, 67, 67,
	249, 142, -1000, 249, 142, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 249, 225, 22, 31, 292, 25, 290, 23, 287,
	8, 0, 282, 164, 371, 19, 989, 18, 278, 37,
	6, 3, 276, 275, 223, 4, 40, 273, 269, 330,
	7, 185, 2, 14, 11, 222, 38, 266, 260, 9,
	67, 176, 27, 259, 256, 255, 57, 131, 1, 254,
	251, 243, 242, 28, 236, 5, 224, 17, 214, 127,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 23, 23, 24, 24, 22, 22,
	26, 26, 26, 25, 25, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 27, 27, 35, 28, 28, 36, 36, 20,
	20, 21, 21, 21, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 38, 38, 41, 41, 31, 31,
	40, 40, 29, 29, 29, 29, 29, 29, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
	37, 37, 32, 32, 42, 42, 42, 42, 42, 42,
	11, 11, 11, 11, 11, 43, 43, 44, 44, 10,
	10, 10, 5, 5, 5, 7, 9, 9, 12, 12,
	12, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 45, 45,
	47, 47, 47, 47, 47, 30, 30, 46, 46, 48,
	48, 48, 48, 48, 48, 16, 16, 49, 49, 50,
	50, 15, 15, 15, 51, 51, 17, 18, 18, 13,
	13, 52, 52, 53, 53, 53, 53, 14, 14, 54,
	54, 55, 19, 19, 56, 56, 57, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 58, 58, 59, 59,
	59, 59, 59, 39, 39, 33, 33, 34, 34,
}

var yyR2 = [...]int8{
	0, 1, 2, 2, 1, 2, 3, 4, 1, 2,
	1, 1, 1, 0, 1, 1, 2, 3, 2, 2,
	3, 6, 3, 6, 7, 7, 8, 8, 8, 8,
	9, 9, 4, 4, 5, 5, 8, 8, 9, 9,
	9, 9, 6, 6, 7, 7, 10, 10, 6, 6,
	4, 4, 1, 2, 1, 1, 2, 1, 1, 1,
	1, 2, 2, 3, 1, 4, 2, 3, 3, 5,
	5, 2, 6, 6, 5, 3, 4, 3, 3, 4,
	3, 3, 4, 6, 1, 2, 1, 1, 0, 1,
	1, 2, 1, 1, 1, 1, 1, 1, 1, 3,
	3, 4, 4, 4, 6, 6, 3, 4, 4, 1,
	0, 1, 1, 2, 1, 1, 1, 1, 1, 1,
	0, 2, 3, 2, 1, 0, 1, 1, 1, 1,
	1, 1, 1, 2, 3, 5, 6, 4, 1, 4,
	4, 2, 1, 2, 2, 1, 4, 1, 3, 5,
	1, 2, 4, 4, 6, 3, 3, 4, 1, 2,
	1, 1, 1, 1, 1, 0, 1, 1, 2, 1,
	1, 1, 1, 1, 1, 0, 2, 0, 1, 1,
	1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
	2, 1, 2, 1, 1, 1, 1, 1, 2, 1,
	2, 1, 1, 2, 1, 2, 1, 2, 2, 2,
	1, 3, 5, 4, 4, 1, 1, 2, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -23, -3, -27, -14, -21, -20, -13,
	-16, -4, -24, -38, 48, 50, -8, -6, -35, 49,
	-15, -5, 27, 33, -41, -58, -45, 53, -17, -19,
	45, -51, -18, -7, 11, 18, -59, -47, 54, 56,
	23, 40, 38, 55, 10, 42, 25, 15, 13, 14,
	-22, -26, 19, 12, 20, -28, -36, 9, 14, -1,
	-24, -37, -32, -42, 13, 14, 17, 31, 35, 37,
	-2, -35, -21, -20, -13, -19, 48, -14, -13, 9,
	-14, -29, -14, 9, -13, -40, 17, 35, 36, 41,
	43, 44, -14, -13, -19, 14, -40, -29, -3, -41,
	-4, -13, -16, -14, -33, -34, -39, -52, 5, 7,
	28, 29, 13, 30, -53, 14, 26, 38, -11, -10,
	22, -44, 46, 51, 52, 28, 21, 35, -40, -11,
	35, -40, -8, -32, 48, 50, 17, 35, 42, 18,
	25, -54, -55, 14, -49, -50, 14, 35, 48, 39,
	-8, -59, 48, -6, -47, -19, 25, 42, -16, -6,
	35, -46, -56, -48, -57, 6, 9, 14, 17, 30,
	31, -15, -17, -9, 37, 13, -26, -3, -36, 14,
	25, -42, -19, -8, 48, 9, -29, -14, 9, 14,
	30, -19, -8, -13, 9, -13, -13, -13, -6, -29,
	-13, -30, -46, -14, 14, -14, 48, -8, -4, -6,
	-13, -14, -11, -11, 48, -53, -40, -43, 42, -10,
	-10, -4, -8, -6, -32, 13, 14, -13, -11, -19,
	-11, -8, 35, -33, -34, -39, 30, -55, -25, 13,
	16, -33, -34, -39, 48, -13, -48, -57, -12, 46,
	6, 35, 48, -15, -8, -31, -40, -14, -13, -13,
	-13, -8, -31, -20, -13, -21, -13, -14, -14, -14,
	-30, -19, -46, -13, -13, -19, -13, 13, -33, -34,
	-10, -10, -8, -46, -13, -40, -40, -33, -34, -39,
	-8, 32, -6, -19, -31, -11, -11, -11, -11, 48,
	-25, 48, 35, -46, 48, 48, 13, -31, -8, -20,
	-13, -14, -19, -32, -31, -8, -14, -29, -13, -19,
	-32, -13, -14, -46, 48, -11, -8, -8, -11, -11,
	48, -11, -8, -33, -34, -33, -34, 48, -13, 13,
	13, 48, -8, -10, -19, -29, -13, -8, -8, -10,
	-19, -13, -29, -8, -8, -8, -19, -33, -34, -11,
	-11, -11, -11, -11, 48, 48, 13, -11, -8, -13,
	-29, -31, -11, -8, -14, -13, -31, -31, -31, 48,
	-31, -19, -13, -8, -31, -19, -14, -8, -8, -8,
	-8, -19, -10, -8, -19, -10, -10, -10, -11, -11,
}

var yyDef = [...]int16{
	0, -2, 1, 0, -2, 0, 150, 0, 0, 0,
	0, 64, 4, 0, -2, -2, 120, 98, 52, 197,
	177, 109, 0, 0, 84, 0, 175, 142, -2, 147,
	54, 0, 183, 132, 86, 87, 216, 158, 186, 202,
	184, 185, 187, 188, 218, -2, -2, 160, 161, 162,
	2, 8, 10, 11, 12, 0, 55, 57, 58, 3,
	4, 0, 111, 112, 114, 115, 116, 117, 118, 119,
	16, 52, 18, 0, 0, 151, 189, 19, 62, 0,
	0, 90, 0, 0, 61, 175, 92, 93, 94, 95,
	96, 97, 0, 165, 0, 0, 0, 90, 66, 84,
	64, 0, 0, 150, -2, -2, 0, 190, 225, 226,
	227, 228, 223, 195, 191, 193, 194, 196, 71, 125,
	0, 0, 124, 129, 130, 131, 127, 128, 0, 175,
	-2, 0, 120, 120, 210, 215, -2, -2, 222, 220,
	221, 198, 199, 201, 176, 178, 179, 180, 13, 0,
	207, 216, 210, 141, 158, 147, 163, 164, 143, 144,
	0, 0, 203, 167, 204, 169, 170, -2, 172, 173,
	174, 181, 182, 133, 0, 219, 9, -2, 56, 58,
	0, 113, 20, 88, -2, 0, 0, 0, 0, 206,
	195, 22, 88, 63, 0, 0, 0, 0, 81, 91,
	155, 0, 0, 156, 171, 0, 0, -2, 78, 98,
	0, 0, 67, 68, 211, 192, 0, 121, 126, 0,
	123, 77, 120, 106, 175, 114, 115, 80, -2, 120,
	99, 120, 118, -2, -2, 0, 224, 200, 6, 14,
	13, 208, 209, 0, 0, 148, 168, 205, 134, 138,
	0, 0, 0, 65, 88, 0, 89, 0, 0, 32,
	0, 88, 0, 0, 59, 60, 0, 0, 33, 0,
	0, 152, 166, 0, 146, 153, 157, 0, 50, 51,
	-2, 79, 120, 0, 155, 0, 0, -2, -2, 0,
	120, 122, 107, 82, 0, 108, 101, 102, 103, 211,
	7, 211, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 34, 0, 0, 0, 0, 0, 0, 35,
	0, 0, 0, 0, 0, 100, 120, 120, 69, 70,
	212, 74, 120, -2, -2, 213, 214, 135, 149, 0,
	0, 137, 120, 42, 21, 0, 0, 88, 120, 43,
	23, 0, 0, 88, 88, 88, 154, 48, 49, 72,
	73, 83, 104, 105, 139, 140, 0, 44, 88, 24,
	0, 0, 45, 88, 25, 0, 0, 0, 0, 136,
	0, 28, 26, 0, 0, 29, 27, 0, 36, 37,
	120, 30, 40, 120, 31, 41, 38, 39, 47, 46,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTimeRanges = yyDollar[1].DateTimeRanges
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = yyDollar[1].DateTimeRanges
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = yyDollar[2].DateTimeRanges
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(yyDollar[1].DateTimeRange)
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = yyDollar[2].DateTimeRanges
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRanges = AppendDateTimeRanges(yyDollar[1].DateTimeRanges, yyDollar[3].DateTimeRange)
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(NewRawDateFromMDsYs(yyDollar[1].string, yyDollar[2].strings, nil)...)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(NewRawDateFromDsMYs(yyDollar[1].strings, yyDollar[2].string, nil)...)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(NewRawDateFromMDsYs(yyDollar[1].string, yyDollar[2].strings, yyDollar[3].string)...)
		}
	case 21:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(append(NewRawDateFromMDsYs(yyDollar[1].string, yyDollar[2].strings, yyDollar[6].string), NewRawDateFromMDsYs(yyDollar[4].string, yyDollar[5].strings, yyDollar[6].string)...)...)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(NewRawDateFromDsMYs(yyDollar[1].strings, yyDollar[2].string, yyDollar[3].string)...)
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(append(NewRawDateFromDsMYs(yyDollar[1].strings, yyDollar[2].string, yyDollar[6].string), NewRawDateFromDsMYs(yyDollar[4].strings, yyDollar[5].string, yyDollar[6].string)...)...)
		}
	case 24:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewRawDateFromMDY(yyDollar[1].string, yyDollar[2].string, nil), NewRawDateFromMDY(yyDollar[1].string, yyDollar[4].string, nil)), NewRangeWithStartEndDates(NewRawDateFromMDY(yyDollar[1].string, yyDollar[5].string, nil), NewRawDateFromMDY(yyDollar[1].string, yyDollar[7].string, nil)))
		}
	case 25:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[1].string, yyDollar[7].string, nil), NewRawDateFromDMY(yyDollar[3].string, yyDollar[7].string, nil)), NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[4].string, yyDollar[7].string, nil), NewRawDateFromDMY(yyDollar[6].string, yyDollar[7].string, nil)))
		}
	case 26:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewRawDateFromMDY(yyDollar[1].string, yyDollar[2].string, nil), NewRawDateFromMDY(yyDollar[1].string, yyDollar[4].string, nil)), NewRangeWithStartEndDates(NewRawDateFromMDY(yyDollar[5].string, yyDollar[6].string, nil), NewRawDateFromMDY(yyDollar[5].string, yyDollar[8].string, nil)))
		}
	case 27:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[1].string, yyDollar[4].string, nil), NewRawDateFromDMY(yyDollar[3].string, yyDollar[4].string, nil)), NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[5].string, yyDollar[8].string, nil), NewRawDateFromDMY(yyDollar[7].string, yyDollar[8].string, nil)))
		}
	case 28:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewRawDateFromMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[8].string), NewRawDateFromMDY(yyDollar[1].string, yyDollar[4].string, yyDollar[8].string)), NewRangeWithStartEndDates(NewRawDateFromMDY(yyDollar[1].string, yyDollar[5].string, yyDollar[8].string), NewRawDateFromMDY(yyDollar[1].string, yyDollar[7].string, yyDollar[8].string)))
		}
	case 29:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[1].string, yyDollar[7].string, yyDollar[8].string), NewRawDateFromDMY(yyDollar[3].string, yyDollar[7].string, yyDollar[8].string)), NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[4].string, yyDollar[7].string, yyDollar[8].string), NewRawDateFromDMY(yyDollar[6].string, yyDollar[7].string, yyDollar[8].string)))
		}
	case 30:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewRawDateFromMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[9].string), NewRawDateFromMDY(yyDollar[1].string, yyDollar[4].string, yyDollar[9].string)), NewRangeWithStartEndDates(NewRawDateFromMDY(yyDollar[5].string, yyDollar[6].string, yyDollar[9].string), NewRawDateFromMDY(yyDollar[5].string, yyDollar[8].string, yyDollar[9].string)))
		}
	case 31:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[1].string, yyDollar[4].string, yyDollar[9].string), NewRawDateFromDMY(yyDollar[3].string, yyDollar[4].string, yyDollar[9].string)), NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[5].string, yyDollar[8].string, yyDollar[9].string), NewRawDateFromDMY(yyDollar[7].string, yyDollar[8].string, yyDollar[9].string)))
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartDate(NewRawDateFromMDY(yyDollar[1].string, yyDollar[2].string, nil)), NewRangeWithStartDate(NewRawDateFromMDY(yyDollar[3].string, yyDollar[4].string, nil)))
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartDate(NewRawDateFromDMY(yyDollar[1].string, yyDollar[2].string, nil)), NewRangeWithStartDate(NewRawDateFromDMY(yyDollar[3].string, yyDollar[4].string, nil)))
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartDate(NewRawDateFromMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string)), NewRangeWithStartDate(NewRawDateFromMDY(yyDollar[3].string, yyDollar[4].string, yyDollar[5].string)))
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartDate(NewRawDateFromDMY(yyDollar[1].string, yyDollar[2].string, nil)), NewRangeWithStartDate(NewRawDateFromDMY(yyDollar[3].string, yyDollar[4].string, yyDollar[5].string)))
		}
	case 36:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRange(NewDateTime(NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil), yyDollar[6].Time, nil), NewDateTime(NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil), yyDollar[8].Time, nil)), NewRange(NewDateTime(NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[6].Time, nil), NewDateTime(NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[8].Time, nil)))
		}
	case 37:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRange(NewDateTime(NewRawDateFromWDMY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[6].Time, nil), NewDateTime(NewRawDateFromWDMY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[8].Time, nil)), NewRange(NewDateTime(NewRawDateFromWDMY(yyDollar[1].string, yyDollar[4].string, yyDollar[5].string, nil), yyDollar[6].Time, nil), NewDateTime(NewRawDateFromWDMY(yyDollar[1].string, yyDollar[4].string, yyDollar[5].string, nil), yyDollar[8].Time, nil)))
		}
	case 38:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRange(NewDateTime(NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil), yyDollar[6].Time, yyDollar[9].TimeZone), NewDateTime(NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil), yyDollar[8].Time, yyDollar[9].TimeZone)), NewRange(NewDateTime(NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[6].Time, yyDollar[9].TimeZone), NewDateTime(NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[8].Time, yyDollar[9].TimeZone)))
		}
	case 39:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRange(NewDateTime(NewRawDateFromWDMY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[6].Time, yyDollar[9].TimeZone), NewDateTime(NewRawDateFromWDMY(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[8].Time, yyDollar[9].TimeZone)), NewRange(NewDateTime(NewRawDateFromWDMY(yyDollar[1].string, yyDollar[4].string, yyDollar[5].string, nil), yyDollar[6].Time, yyDollar[9].TimeZone), NewDateTime(NewRawDateFromWDMY(yyDollar[1].string, yyDollar[4].string, yyDollar[5].string, nil), yyDollar[8].Time, yyDollar[9].TimeZone)))
		}
	case 40:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRange(NewDateTime(NewRawDateFromMDY(yyDollar[1].string, yyDollar[2].string, nil), yyDollar[6].Time, yyDollar[9].TimeZone), NewDateTime(NewRawDateFromMDY(yyDollar[1].string, yyDollar[2].string, nil), yyDollar[8].Time, yyDollar[9].TimeZone)), NewRange(NewDateTime(NewRawDateFromMDY(yyDollar[1].string, yyDollar[4].string, nil), yyDollar[6].Time, yyDollar[9].TimeZone), NewDateTime(NewRawDateFromMDY(yyDollar[1].string, yyDollar[4].string, nil), yyDollar[8].Time, yyDollar[9].TimeZone)))
		}
	case 41:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRange(NewDateTime(NewRawDateFromDMY(yyDollar[1].string, yyDollar[4].string, nil), yyDollar[6].Time, yyDollar[9].TimeZone), NewDateTime(NewRawDateFromDMY(yyDollar[1].string, yyDollar[4].string, nil), yyDollar[8].Time, yyDollar[9].TimeZone)), NewRange(NewDateTime(NewRawDateFromDMY(yyDollar[3].string, yyDollar[4].string, nil), yyDollar[6].Time, yyDollar[9].TimeZone), NewDateTime(NewRawDateFromDMY(yyDollar[3].string, yyDollar[4].string, nil), yyDollar[8].Time, yyDollar[9].TimeZone)))
		}
	case 42:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesFromDatesTimeRange(NewRawDateFromMDsYs(yyDollar[1].string, yyDollar[2].strings, nil), yyDollar[3].Time, yyDollar[5].Time, yyDollar[6].TimeZone)
		}
	case 43:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesFromDatesTimeRange(NewRawDateFromDsMYs(yyDollar[1].strings, yyDollar[2].string, nil), yyDollar[3].Time, yyDollar[5].Time, yyDollar[6].TimeZone)
		}
	case 44:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesFromDatesTimeRange(NewRawDateFromMDsYs(yyDollar[1].string, yyDollar[2].strings, yyDollar[3].string), yyDollar[4].Time, yyDollar[6].Time, yyDollar[7].TimeZone)
		}
	case 45:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesFromDatesTimeRange(NewRawDateFromDsMYs(yyDollar[1].strings, yyDollar[2].string, yyDollar[3].string), yyDollar[4].Time, yyDollar[6].Time, yyDollar[7].TimeZone)
		}
	case 46:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesFromDatesTimeRange(append(NewRawDateFromDsMYs(yyDollar[1].strings, yyDollar[2].string, yyDollar[6].string), NewRawDateFromDsMYs(yyDollar[4].strings, yyDollar[5].string, yyDollar[6].string)...), yyDollar[7].Time, yyDollar[9].Time, yyDollar[10].TimeZone)
		}
	case 47:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesFromDatesTimeRange(append(NewRawDateFromMDsYs(yyDollar[1].string, yyDollar[2].strings, yyDollar[6].string), NewRawDateFromMDsYs(yyDollar[4].string, yyDollar[5].strings, yyDollar[6].string)...), yyDollar[7].Time, yyDollar[9].Time, yyDollar[10].TimeZone)
		}
	case 48:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStart(yyDollar[1].DateTime), NewRangeWithStart(NewDateTime(yyDollar[1].DateTime.Date, NewAMTime(yyDollar[3].string, yyDollar[5].string, nil, nil), yyDollar[1].DateTime.TimeZone)))
		}
	case 49:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStart(yyDollar[1].DateTime), NewRangeWithStart(NewDateTime(yyDollar[1].DateTime.Date, NewPMTime(yyDollar[3].string, yyDollar[5].string, nil, nil), yyDollar[1].DateTime.TimeZone)))
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStart(yyDollar[1].DateTime), NewRangeWithStart(NewDateTime(yyDollar[1].DateTime.Date, NewAMTime(yyDollar[3].string, nil, nil, nil), yyDollar[1].DateTime.TimeZone)))
		}
	case 51:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStart(yyDollar[1].DateTime), NewRangeWithStart(NewDateTime(yyDollar[1].DateTime.Date, NewPMTime(yyDollar[3].string, nil, nil, nil), yyDollar[1].DateTime.TimeZone)))
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strings = []string{yyDollar[1].string}
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.strings = []string{yyDollar[1].string, yyDollar[2].string}
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[2].string)
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[3].string)
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStart(yyDollar[1].DateTime)
		}
	case 65:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRange = yyDollar[1].DateTimeRange
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRange = yyDollar[2].DateTimeRange
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStart(NewDateTime(nil, NewAMTime(yyDollar[1].string, nil, nil, nil), yyDollar[3].TimeZone))
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStart(NewDateTime(nil, NewPMTime(yyDollar[1].string, nil, nil, nil), yyDollar[3].TimeZone))
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStart(NewDateTime(nil, NewAMTime(yyDollar[1].string, yyDollar[3].string, nil, nil), yyDollar[5].TimeZone))
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStart(NewDateTime(nil, NewPMTime(yyDollar[1].string, yyDollar[3].string, nil, nil), yyDollar[5].TimeZone))
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStart(NewDateTime(nil, NewTime(yyDollar[1].string, nil, nil, nil), yyDollar[2].TimeZone))
		}
	case 72:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(nil, NewAMTime(yyDollar[1].string, nil, nil, nil), yyDollar[3].TimeZone), NewDateTime(nil, yyDollar[5].Time, yyDollar[6].TimeZone))
		}
	case 73:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(nil, NewPMTime(yyDollar[1].string, nil, nil, nil), yyDollar[3].TimeZone), NewDateTime(nil, yyDollar[5].Time, yyDollar[6].TimeZone))
		}
	case 74:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(nil, NewTime(yyDollar[1].string, nil, nil, nil), yyDollar[2].TimeZone), NewDateTime(nil, yyDollar[4].Time, yyDollar[5].TimeZone))
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(yyDollar[1].DateTime, NewDateTime(yyDollar[1].DateTime.Date, yyDollar[3].Time, yyDollar[1].DateTime.TimeZone))
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(yyDollar[1].DateTime.Date, yyDollar[1].DateTime.Time, yyDollar[4].TimeZone), NewDateTime(yyDollar[1].DateTime.Date, yyDollar[3].Time, yyDollar[4].TimeZone))
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(yyDollar[3].DateTime.Date, yyDollar[1].Time, yyDollar[3].DateTime.TimeZone), yyDollar[3].DateTime)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(yyDollar[1].DateTime, yyDollar[3].DateTime)
		}
	case 79:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(yyDollar[1].DateTime.Date, yyDollar[1].DateTime.Time, yyDollar[4].TimeZone), NewDateTime(yyDollar[3].DateTime.Date, yyDollar[3].DateTime.Time, yyDollar[4].TimeZone))
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(yyDollar[1].Date, NewRawDateFromDMY(yyDollar[3].string, nil, nil))
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewRawDateFromDMY(yyDollar[1].string, nil, nil), yyDollar[3].Date)
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(yyDollar[1].Date, NewRawDateFromMDY(nil, yyDollar[3].string, yyDollar[4].string))
		}
	case 83:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(yyDollar[1].Date, yyDollar[2].Time, yyDollar[3].TimeZone), NewDateTime(yyDollar[1].Date, yyDollar[5].Time, yyDollar[6].TimeZone))
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTime = NewDateTimeWithDate(yyDollar[1].Date)
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, nil, yyDollar[3].TimeZone)
		}
	case 100:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, yyDollar[2].Time, yyDollar[3].TimeZone)
		}
	case 101:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, yyDollar[3].Time, yyDollar[4].TimeZone)
		}
	case 102:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, NewAMTime(yyDollar[2].string, nil, nil, nil), yyDollar[4].TimeZone)
		}
	case 103:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, NewPMTime(yyDollar[2].string, nil, nil, nil), yyDollar[4].TimeZone)
		}
	case 104:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, NewAMTime(yyDollar[2].string, yyDollar[4].string, nil, nil), yyDollar[6].TimeZone)
		}
	case 105:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, NewPMTime(yyDollar[2].string, yyDollar[4].string, nil, nil), yyDollar[6].TimeZone)
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[3].Date, yyDollar[1].Time, yyDollar[2].TimeZone)
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[4].Date, yyDollar[1].Time, yyDollar[2].TimeZone)
		}
	case 108:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(NewRawDateFromDMY(yyDollar[1].Date.Day, yyDollar[1].Date.Month, yyDollar[3].string), yyDollar[2].Time, yyDollar[4].TimeZone)
		}
	case 120:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.TimeZone = nil
		}
	case 121:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.TimeZone = yyDollar[1].TimeZone
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.TimeZone = yyDollar[2].TimeZone
		}
	case 123:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.TimeZone = yyDollar[2].TimeZone
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = nil
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(yyDollar[1].string, nil, nil)
		}
	case 130:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(nil, yyDollar[1].string, nil)
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(nil, "P", nil)
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTime = NewDateTimeWithDate(yyDollar[1].Date)
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, yyDollar[2].Time, nil)
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, yyDollar[2].Time, yyDollar[3].TimeZone)
		}
	case 135:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromDMY(yyDollar[5].string, yyDollar[3].string, yyDollar[1].string)
		}
	case 136:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[2].string, yyDollar[4].string, yyDollar[6].string, nil)
		}
	case 137:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[2].string, yyDollar[4].string, nil, nil)
		}
	case 138:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = nil
		}
	case 139:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(nil, nil, "+"+yyDollar[2].string+":"+yyDollar[4].string)
		}
	case 140:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(nil, nil, "-"+yyDollar[2].string+":"+yyDollar[4].string)
		}
	case 141:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Date = yyDollar[2].Date
		}
	case 142:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromRelative(yyDollar[1].string)
		}
	case 143:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromRelative(yyDollar[1].string)
		}
	case 144:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Date = yyDollar[2].Date
		}
	case 145:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromRelative(yyDollar[1].string)
		}
	case 146:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromAmbiguous(yyDollar[1].string, yyDollar[2].string, yyDollar[4].string, nil)
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromDMY(nil, nil, yyDollar[1].string)
		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromDMY(nil, yyDollar[3].string, yyDollar[1].string)
		}
	case 149:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromDMY(yyDollar[5].string, yyDollar[3].string, yyDollar[1].string)
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromMDY(yyDollar[1].string, nil, nil)
		}
	case 151:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromMDY(yyDollar[1].string, nil, yyDollar[2].string)
		}
	case 152:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[4].string)
		}
	case 153:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromWDMY(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[4].string)
		}
	case 154:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromAmbiguous(yyDollar[1].string, yyDollar[2].string, yyDollar[4].string, yyDollar[6].string)
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromWMDY(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil)
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromWDMY(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil)
		}
	case 157:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Date = NewRawDateFromWDMY(yyDollar[1].string, yyDollar[4].string, yyDollar[3].string, yyDollar[2].string)
		}
	case 175:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.string = ""
		}
	case 181:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.string = yyDollar[2].string
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = "TH"
		}
	case 207:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Time = yyDollar[2].Time
		}
	case 208:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Time = NewAMTime(yyDollar[1].string, nil, nil, nil)
		}
	case 209:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Time = NewPMTime(yyDollar[1].string, nil, nil, nil)
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[1].string, nil, nil, nil)
		}
	case 211:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[1].string, yyDollar[3].string, nil, nil)
		}
	case 212:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[1].string, yyDollar[3].string, yyDollar[5].string, nil)
		}
	case 213:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Time = NewAMTime(yyDollar[1].string, yyDollar[3].string, nil, nil)
		}
	case 214:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Time = NewPMTime(yyDollar[1].string, yyDollar[3].string, nil, nil)
		}
	case 215:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[1].string, nil, nil, nil)
		}
	}
	goto yystack /* stack new state and value */
}
