package datetime

import (
	"errors"
	"regexp"
	"strconv"
	"strings"

	"go/scanner"
	"go/token"

	"github.com/findyourpaths/phil/glr"
	"github.com/microcosm-cc/bluemonday"
)

// datetimeLexer implements yyLexer interface for the parser generated by goyacc,
// and also GLR's Lexer interface.
type datetimeLexer struct {
	lval    *yySymType
	scanner scanner.Scanner
	err     error
	root    *DateTimeRanges
}

// Match a digit on one side and a letter on another. Used to separate `12pm`.
var boundaryRE1 = regexp.MustCompile(`([[:alpha:]])([[:^alpha:]])`)
var boundaryRE2 = regexp.MustCompile(`([[:^alpha:]])([[:alpha:]])`)

// var spacifyRE = regexp.MustCompile(`\s*\b(.|-)\b\s*`)
var spacifyRE = regexp.MustCompile(`(?:^|\s*\b)(.|-)(?:\b\s*|$)`)

// ianaTimezoneRE matches IANA timezone paths like "US/Eastern", "America/New_York".
var ianaTimezoneRE = regexp.MustCompile(`[A-Z][a-zA-Z_]+/[A-Z][a-zA-Z_]+`)

// dayNumberRE matches "Day N" session numbering (e.g. "Day 1", "Day 2") that interferes
// with date parsing when the number gets consumed as a Time (hour).
var dayNumberRE = regexp.MustCompile(`(?i)\bday\s+\d\b`)

// markdownBoldRE matches markdown bold formatting (**...**) which often contains
// title text with tokens like "and", ":", "+" that interfere with date parsing.
var markdownBoldRE = regexp.MustCompile(`\*\*[^*]+\*\*`)

// circaRE matches "ca." (German abbreviation for "circa") followed by a digit.
// Without stripping, "ca.12" becomes ".12" (FLOAT token) after boundary splitting,
// which prevents the "12" from being parsed as INT for time.
var circaRE = regexp.MustCompile(`(?i)\bca\.(\d)`)

// twoDigitYearRE matches M/D/YY or D/M/YY patterns where the year is exactly 2 digits.
// The negative lookahead (?!\d) prevents matching 4-digit years like "2/3/2023".
var twoDigitYearRE = regexp.MustCompile(`(\d{1,2}/\d{1,2}/)(\d{2})(?:\D|$)`)

// expandTwoDigitYears replaces 2-digit years in slash-separated date patterns
// with 4-digit years (00-49 → 2000s, 50-99 → 1900s) before boundary splitting
// would separate the components.
func expandTwoDigitYears(input string) string {
	return twoDigitYearRE.ReplaceAllStringFunc(input, func(match string) string {
		sub := twoDigitYearRE.FindStringSubmatch(match)
		yy, _ := strconv.Atoi(sub[2])
		if yy < 50 {
			yy += 2000
		} else {
			yy += 1900
		}
		// Preserve the trailing non-digit character
		trail := match[len(sub[1])+len(sub[2]):]
		return sub[1] + strconv.Itoa(yy) + trail
	})
}

// replaceIANATimezones replaces IANA timezone paths with their standard abbreviation
// before input preprocessing splits them at the "/".
func replaceIANATimezones(input string) string {
	return ianaTimezoneRE.ReplaceAllStringFunc(input, func(match string) string {
		if tz, _ := timezoneTZ.GetTzInfo(match); tz != nil {
			return tz.ShortGeneric()
		}
		return match
	})
}

func NewDatetimeLexer(input string) *datetimeLexer {
	// yyDebug = 3
	debugf("in before processing: %q\n", input)
	// input = daysRE.ReplaceAllString(input, ``)
	input = replaceIANATimezones(input)
	input = expandTwoDigitYears(input)
	input = dayNumberRE.ReplaceAllString(input, "")
	input = markdownBoldRE.ReplaceAllString(input, "")
	input = circaRE.ReplaceAllString(input, "$1")
	input = boundaryRE1.ReplaceAllString(input, `$1 $2`)
	input = boundaryRE2.ReplaceAllString(input, `$1 $2`)
	input = spacifyRE.ReplaceAllString(input, ` $1 `)
	// input = strings.TrimPrefix(input, "When ")
	// input = strings.TrimPrefix(input, "when ")
	input = strings.Replace(input, " ' ", " ", -1)
	input = CleanTextLine(input)
	// input = strings.Replace(input, " &#39; ", "\\'", -1)
	debugf("input after processing: %q\n", input)

	l := &datetimeLexer{
		lval: &yySymType{},
	}
	l.scanner = glr.NewLexerScanner(l, input)
	return l
}

var whitespacesRE = regexp.MustCompile(`\s+`)

func CleanTextLine(s string) string {
	r := bluemonday.StrictPolicy().AddSpaceWhenStrippingTag(true).Sanitize(s)
	r = strings.ReplaceAll(r, "\u00a0", " ")
	r = whitespacesRE.ReplaceAllString(r, " ")
	r = strings.TrimSpace(r)
	return r
}

func (l *datetimeLexer) NextToken(pos int) (string, string, bool) {
	val := l.Lex(l.lval)
	sym := l.lval.string
	if val >= 57343 {
		sym = yyToknames[val-57343]
	}
	// fmt.Printf("sym: %q, l.lval.string: %q, val: %d\n", sym, l.lval.string, val)
	return sym, l.lval.string, val >= 0
}

func (l *datetimeLexer) Error(msg string) {
	l.err = errors.New(msg)
}

// yySymType is generated by goyacc
func (l *datetimeLexer) Lex(lval *yySymType) int {
	for {
		_, tok, lit := l.scanner.Scan()
		features := ""
		if tok == token.ILLEGAL {
			features += " ILLEGAL"
		}
		if tok == token.IDENT {
			features += " IDENT"
		}
		debugf("scanned literal: %q as token: %q%s\n", lit, tok, features)

		// Skip whitespace and semicolons
		if tok == token.SEMICOLON {
			continue
		}
		if tok == token.EOF {
			lval.string = "$end"
			return -1
		}

		lval.string = lit
		if lit == "" {
			lval.string = tok.String()
		}
		// fmt.Printf("lval.string: %#v\n", lval.string)

		switch tok {

		case token.ILLEGAL:
			litl := strings.ToLower(lit)
			switch litl {
			case "@":
				return AMP

			case "–":
				return SUB

			case "—":
				return SUB

			default:
				return ILLEGAL
			}

		case token.IDENT:
			lowLit := strings.ToLower(lit)
			switch lowLit {
			case "a":
				return A
			case "am":
				return AM
			case "and":
				return AND
			case "at":
				return AT
			case "beginning":
				return BEGINNING
			case "calendar":
				return CALENDAR
			// "date" treated as IDENT to avoid "Day 2" being consumed as DATE
			// token (DatePrefix) which kills parser branches that could skip it
			// as noise. "Date:" tests still work because COLON alone is DatePrefix.
			// case "date":
			// 	return DATE
			case "dates":
				return DATES
			case "from":
				return FROM
			case "google":
				return GOOGLE
			case "ics":
				return ICS
			case "in":
				return IN
			case "midnight":
				return TIME_NAME
			// "next" treated as IDENT to avoid consuming it as WeekdayPrefix
		// when it appears as noise in sentences (e.g. "Our next cohort...").
		// The WeekdayPrefix grammar rule discards the prefix anyway.
		// case "next":
		// 	return NEXT
			case "noon":
				return TIME_NAME
			case "of":
				return OF
			case "on":
				return ON
			case "part":
				return PART
			case "p":
				return P
			case "pm":
				return PM
			case "save":
				return SAVE
			case "through":
				return THROUGH
			case "t":
				return T
			case "th":
				return TH
			case "the":
				return THE
			case "till":
				return TILL
			case "this":
				return THIS
			case "time":
				return TIME
			case "to":
				return TO
			case "today":
				return RELATIVE_DAY
			case "tomorrow":
				return RELATIVE_DAY
			case "until":
				return UNTIL
			case "when":
				return WHEN
			case "yesterday":
				return RELATIVE_DAY
			case "z":
				return Z

			default:
				if ordinals[lowLit] {
					return ORD_IND
				}

				if _, found := monthsByNames[lowLit]; found {
					return MONTH_NAME
				}

				if _, found := weekdaysByNames[lowLit]; found {
					if len(lowLit) < 4 {
						return WEEKDAY_SHORT_NAME
					}
					return WEEKDAY_NAME
				}

				if _, found := timeZoneAbbreviationsByNames[lowLit]; found {
					return TIME_ZONE
				}

				upLit := strings.ToUpper(lit)
				// tz, err := tzTimezone.GetTzAbbreviationInfo(upLit)
				// fmt.Println("upLit", upLit, "tz", tz, "err", err)
				// Ignore single-char timezone abbreviations - too many false positives (e.g., "S" from "Maggiano's")
				if len(upLit) > 1 {
					if tz, _ := timezoneTZ.GetTzAbbreviationInfo(upLit); tz != nil {
						return TIME_ZONE_ABBREV
					}
				}
				if tz, _ := timezoneTZ.GetTzInfo(upLit); tz != nil {
					return TIME_ZONE
				}

				return IDENT
			}

		case token.INT:
			if len(lit) == 4 &&
				(strings.HasPrefix(lit, "17") ||
					strings.HasPrefix(lit, "18") ||
					strings.HasPrefix(lit, "19") ||
					strings.HasPrefix(lit, "20") ||
					strings.HasPrefix(lit, "21")) {
				return YEAR
			}
			return INT

		case token.ADD:
			return ADD
		case token.AND:
			return AND
		case token.COLON:
			return COLON
		case token.COMMA:
			return COMMA
		case token.DEC:
			return DEC
		case token.LPAREN:
			return LPAREN
		case token.PERIOD:
			return PERIOD
		case token.QUO:
			return QUO
		case token.RPAREN:
			return RPAREN
		case token.SEMICOLON:
			return SEMICOLON
		case token.SUB:
			return SUB
		default:
			return ILLEGAL
		}
	}
}
