// Code generated by goyacc -l -o parse_yacc.go -v parse_yacc.states.txt parse_yacc.y. DO NOT EDIT.
package datetime

import __yyfmt__ "fmt"

type yySymType struct {
	yys            int
	DateTimeRanges *DateTimeRanges
	DateTimeRange  *DateTimeRange
	DateTime       *DateTime
	Date           *Date
	Time           *Time
	TimeZone       *TimeZone
	string         string
	strings        []string
}

const ILLEGAL = 57346
const A = 57347
const ADD = 57348
const AM = 57349
const AMP = 57350
const AND = 57351
const AT = 57352
const BEGINNING = 57353
const CALENDAR = 57354
const COLON = 57355
const COMMA = 57356
const DATE = 57357
const DATES = 57358
const DEC = 57359
const FROM = 57360
const GOOGLE = 57361
const ICS = 57362
const IN = 57363
const LPAREN = 57364
const OF = 57365
const ON = 57366
const ORD_IND = 57367
const PART = 57368
const P = 57369
const PM = 57370
const PERIOD = 57371
const QUO = 57372
const RPAREN = 57373
const SAVE = 57374
const SEMICOLON = 57375
const SUB = 57376
const THROUGH = 57377
const T = 57378
const TH = 57379
const THE = 57380
const TILL = 57381
const TIME = 57382
const TO = 57383
const UNTIL = 57384
const WHEN = 57385
const Z = 57386
const IDENT = 57387
const INT = 57388
const MONTH_NAME = 57389
const TIME_NAME = 57390
const TIME_ZONE = 57391
const TIME_ZONE_ABBREV = 57392
const WEEKDAY_NAME = 57393
const YEAR = 57394

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ILLEGAL",
	"A",
	"ADD",
	"AM",
	"AMP",
	"AND",
	"AT",
	"BEGINNING",
	"CALENDAR",
	"COLON",
	"COMMA",
	"DATE",
	"DATES",
	"DEC",
	"FROM",
	"GOOGLE",
	"ICS",
	"IN",
	"LPAREN",
	"OF",
	"ON",
	"ORD_IND",
	"PART",
	"P",
	"PM",
	"PERIOD",
	"QUO",
	"RPAREN",
	"SAVE",
	"SEMICOLON",
	"SUB",
	"THROUGH",
	"T",
	"TH",
	"THE",
	"TILL",
	"TIME",
	"TO",
	"UNTIL",
	"WHEN",
	"Z",
	"IDENT",
	"INT",
	"MONTH_NAME",
	"TIME_NAME",
	"TIME_ZONE",
	"TIME_ZONE_ABBREV",
	"WEEKDAY_NAME",
	"YEAR",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 18,
	17, 144,
	34, 144,
	35, 144,
	39, 144,
	41, 144,
	42, 144,
	46, 144,
	47, 144,
	-2, 169,
	-1, 38,
	10, 181,
	18, 181,
	48, 181,
	-2, 134,
	-1, 39,
	10, 180,
	18, 180,
	48, 180,
	-2, 133,
	-1, 89,
	27, 102,
	49, 102,
	50, 102,
	-2, 74,
	-1, 140,
	9, 140,
	14, 140,
	17, 140,
	29, 140,
	30, 140,
	46, 140,
	-2, 161,
	-1, 168,
	1, 48,
	9, 48,
	12, 48,
	14, 48,
	19, 48,
	20, 48,
	-2, 94,
	-1, 183,
	10, 69,
	18, 69,
	24, 69,
	40, 69,
	46, 69,
	48, 69,
	-2, 80,
	-1, 220,
	9, 141,
	14, 141,
	29, 141,
	30, 141,
	-2, 73,
	-1, 225,
	1, 49,
	9, 49,
	12, 49,
	14, 49,
	19, 49,
	20, 49,
	-2, 99,
}

const yyPrivate = 57344

const yyLast = 738

var yyAct = [...]int16{
	27, 216, 175, 137, 226, 191, 112, 59, 97, 95,
	111, 75, 110, 7, 138, 107, 12, 19, 113, 84,
	56, 36, 8, 17, 60, 14, 60, 130, 306, 57,
	36, 131, 6, 92, 15, 6, 291, 6, 85, 61,
	63, 94, 73, 49, 139, 80, 139, 60, 17, 166,
	125, 166, 220, 36, 141, 90, 91, 151, 29, 4,
	290, 127, 158, 156, 142, 143, 142, 143, 272, 68,
	69, 268, 30, 78, 70, 219, 71, 72, 60, 17,
	80, 59, 267, 75, 244, 130, 243, 36, 204, 36,
	154, 196, 149, 169, 177, 180, 17, 190, 123, 183,
	173, 124, 168, 135, 186, 44, 164, 167, 148, 174,
	145, 170, 241, 231, 172, 35, 67, 193, 170, 176,
	202, 185, 188, 129, 10, 181, 182, 10, 189, 10,
	75, 50, 59, 68, 69, 67, 51, 82, 70, 198,
	71, 72, 128, 34, 156, 60, 17, 46, 203, 147,
	165, 199, 68, 69, 45, 47, 120, 70, 201, 71,
	72, 195, 108, 292, 218, 222, 77, 121, 126, 198,
	36, 157, 82, 212, 23, 37, 64, 98, 130, 122,
	271, 99, 210, 104, 205, 270, 186, 209, 79, 105,
	234, 245, 214, 215, 100, 192, 227, 235, 101, 238,
	102, 237, 146, 236, 159, 103, 135, 225, 249, 250,
	9, 96, 230, 25, 152, 24, 255, 58, 62, 212,
	65, 74, 136, 198, 81, 153, 239, 130, 246, 218,
	11, 265, 264, 162, 53, 259, 263, 106, 248, 259,
	222, 218, 252, 162, 109, 16, 198, 273, 2, 26,
	162, 55, 276, 277, 54, 87, 1, 179, 266, 81,
	52, 176, 232, 287, 130, 66, 198, 62, 13, 65,
	165, 289, 186, 242, 48, 160, 259, 161, 76, 259,
	83, 5, 280, 297, 163, 3, 43, 200, 144, 281,
	298, 171, 284, 74, 307, 31, 309, 288, 230, 262,
	312, 313, 314, 315, 316, 317, 22, 186, 0, 319,
	295, 320, 0, 67, 300, 301, 0, 303, 304, 0,
	321, 0, 162, 311, 155, 323, 326, 0, 310, 325,
	68, 69, 298, 29, 67, 70, 0, 71, 72, 0,
	194, 257, 60, 0, 0, 260, 197, 30, 0, 324,
	0, 68, 69, 322, 0, 0, 70, 0, 71, 72,
	0, 0, 0, 60, 206, 207, 208, 0, 93, 86,
	211, 213, 0, 0, 92, 0, 223, 0, 224, 0,
	253, 184, 283, 228, 162, 286, 229, 139, 162, 0,
	0, 88, 166, 0, 0, 141, 90, 91, 0, 0,
	162, 0, 0, 0, 0, 0, 240, 142, 143, 0,
	0, 114, 0, 115, 274, 0, 211, 247, 0, 118,
	251, 279, 65, 62, 60, 254, 0, 256, 258, 217,
	221, 139, 261, 116, 117, 187, 166, 155, 0, 141,
	37, 32, 294, 41, 42, 40, 0, 0, 33, 233,
	0, 142, 143, 269, 39, 0, 20, 0, 0, 275,
	0, 0, 21, 0, 278, 0, 0, 29, 282, 17,
	38, 285, 162, 28, 0, 0, 18, 17, 25, 0,
	0, 30, 36, 0, 0, 293, 67, 0, 0, 0,
	296, 0, 299, 37, 217, 302, 41, 42, 40, 0,
	67, 104, 0, 68, 69, 308, 0, 39, 70, 0,
	71, 72, 0, 0, 0, 0, 318, 68, 69, 0,
	29, 0, 70, 38, 71, 72, 0, 0, 0, 96,
	17, 25, 0, 0, 30, 36, 50, 37, 32, 0,
	41, 150, 40, 0, 0, 33, 0, 0, 0, 0,
	0, 39, 0, 0, 305, 37, 32, 0, 41, 42,
	40, 0, 0, 33, 29, 0, 0, 38, 0, 39,
	0, 0, 0, 18, 17, 25, 0, 0, 30, 36,
	0, 0, 29, 0, 0, 38, 0, 0, 28, 0,
	0, 18, 17, 25, 0, 0, 30, 36, 37, 32,
	0, 41, 42, 40, 0, 0, 33, 0, 0, 139,
	0, 0, 39, 0, 166, 0, 0, 141, 0, 0,
	178, 42, 40, 0, 99, 29, 0, 0, 38, 142,
	143, 132, 0, 0, 18, 17, 25, 100, 0, 30,
	36, 101, 0, 102, 29, 67, 0, 133, 0, 93,
	86, 0, 0, 0, 17, 92, 0, 0, 30, 36,
	0, 0, 89, 69, 41, 42, 40, 70, 0, 71,
	72, 0, 88, 0, 0, 132, 139, 90, 91, 0,
	0, 140, 0, 0, 141, 0, 37, 0, 29, 98,
	0, 133, 0, 99, 104, 0, 142, 143, 17, 0,
	105, 134, 30, 36, 0, 114, 100, 115, 0, 0,
	101, 0, 102, 118, 120, 139, 103, 0, 0, 0,
	140, 0, 96, 141, 25, 121, 0, 116, 117, 119,
	0, 0, 0, 0, 0, 142, 143, 122,
}

var yyPact = [...]int16{
	430, 135, 122, 430, -1000, 545, -22, 32, -24, 317,
	1, -1000, 469, 588, 628, 676, -1000, 148, 700, -1000,
	52, 63, -1000, -1000, 165, -1000, 651, 667, -1000, -1000,
	-1000, 74, -1000, -1000, -1000, -1000, -1000, -1000, 189, -1000,
	-1000, -1000, -1000, 135, -1000, -1000, -1000, -1000, 527, -1000,
	-1000, -1000, 135, -1000, 122, -1000, -22, 205, 99, 130,
	142, -31, -1000, 195, -20, -1000, 317, -1000, -1000, -1000,
	-1000, -1000, -1000, -20, 422, 49, 483, -1000, -1000, -1000,
	-22, 469, 1, 483, 607, 55, 6, 6, -1000, -1000,
	-1000, -1000, -1000, -1000, 347, 676, 406, -1000, -1000, -1000,
	-1000, -1000, -1000, 189, -1000, -1000, 148, -1000, -1000, 142,
	-1000, -1000, 51, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 182, 101, -1000, -1000, -1000, -1000, 1,
	706, -31, -1000, -1000, 45, 378, 130, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 114, 42, -1000, -1000, -1000, -1000,
	-1000, 130, -24, -20, -20, 99, -1000, -1000, 130, -20,
	32, -24, -1000, 35, 118, 378, -1000, -20, 347, -1000,
	676, 469, -20, -1000, 347, -20, -1000, 607, -1000, -1000,
	-1000, 82, -1000, 469, -1000, 347, -1000, -1000, -1000, -1000,
	406, -1000, -1000, 182, 422, -20, 78, 600, -1000, -1000,
	-1000, -1000, 40, 38, 178, -20, 32, -31, -31, -20,
	-24, -20, -20, 469, -20, -31, -20, 296, 130, 600,
	-1000, 296, 130, 600, -1000, 55, 607, 347, 118, 600,
	-1000, -1000, 165, 469, -1000, 36, -1000, -1000, -1000, -31,
	-31, 25, 378, 172, 167, 22, -31, 469, -20, 130,
	130, -31, -31, -20, 469, 130, 165, 32, 21, -1000,
	32, 21, 37, 607, -1000, -24, 347, -1000, -1000, -1000,
	14, -10, 150, 130, -20, 469, 130, 130, -24, -20,
	164, -20, -24, -24, -20, -24, -24, 130, 469, -1000,
	-1000, -1000, -18, -31, -20, -31, -24, 165, 164, -31,
	-31, -31, -31, -31, -31, 317, -1000, 130, -31, 130,
	-31, -1000, 130, 130, 130, 130, 130, 130, 600, 130,
	130, -24, 164, 165, 347, -31, 130,
}

var yyPgo = [...]int16{
	0, 256, 248, 59, 16, 306, 34, 295, 25, 288,
	38, 4, 287, 210, 31, 17, 123, 0, 22, 13,
	286, 285, 230, 5, 105, 281, 274, 166, 1, 2,
	245, 43, 268, 265, 262, 174, 9, 8, 257, 255,
	249, 75, 115, 3, 244, 18, 237, 15, 222, 14,
	215, 12, 10, 6, 143,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 21, 21, 22, 22, 20, 20,
	24, 24, 24, 23, 23, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 25, 25, 30, 26, 26,
	31, 31, 18, 18, 19, 19, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 32, 32, 35, 35, 34,
	34, 33, 33, 27, 27, 27, 27, 27, 27, 4,
	4, 4, 4, 4, 4, 29, 29, 36, 36, 37,
	37, 37, 37, 37, 11, 11, 11, 11, 11, 38,
	38, 39, 39, 10, 10, 10, 5, 5, 5, 7,
	9, 12, 12, 12, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 40, 40, 42,
	42, 42, 42, 42, 42, 28, 28, 41, 41, 43,
	43, 43, 43, 43, 13, 13, 44, 44, 45, 45,
	45, 45, 14, 14, 46, 46, 47, 17, 17, 48,
	48, 49, 16, 16, 15, 15, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 50, 50, 54, 54, 54,
	54, 54, 53, 53, 51, 51, 52, 52,
}

var yyR2 = [...]int8{
	0, 1, 2, 2, 1, 2, 3, 4, 1, 2,
	1, 1, 1, 0, 1, 1, 2, 3, 2, 2,
	3, 6, 3, 6, 7, 7, 8, 8, 8, 8,
	9, 9, 4, 5, 8, 1, 2, 1, 1, 2,
	1, 1, 1, 1, 2, 2, 1, 2, 3, 4,
	3, 3, 4, 4, 5, 5, 6, 8, 8, 8,
	8, 8, 8, 14, 6, 1, 2, 1, 1, 0,
	1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
	3, 4, 3, 4, 1, 0, 1, 1, 2, 1,
	1, 1, 1, 1, 0, 2, 3, 2, 1, 0,
	1, 1, 1, 1, 1, 1, 1, 2, 3, 5,
	6, 1, 4, 4, 2, 4, 1, 3, 5, 1,
	2, 4, 4, 6, 3, 3, 4, 1, 2, 1,
	1, 1, 1, 1, 1, 0, 1, 1, 2, 1,
	1, 1, 1, 1, 1, 2, 1, 2, 1, 1,
	1, 1, 1, 2, 1, 2, 1, 1, 2, 1,
	2, 1, 0, 1, 1, 1, 2, 2, 2, 1,
	3, 5, 4, 4, 1, 1, 2, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -21, -3, -25, -14, -19, -18, -13,
	-16, -22, -4, -32, -8, -6, -30, 47, 46, -15,
	26, 32, -5, -35, -50, 48, -40, -17, 43, 37,
	51, -7, 11, 18, -54, -42, 52, 10, 40, 24,
	15, 13, 14, -20, -24, 19, 12, 20, -26, -31,
	9, 14, -1, -22, -2, -30, -19, -18, -13, -17,
	46, -14, -13, -14, -27, -13, -33, 17, 34, 35,
	39, 41, 42, -14, -13, -17, -33, -27, -3, -35,
	-14, -13, -16, -33, -11, -10, 22, -39, 44, 34,
	49, 50, 27, 21, -8, -36, 46, -37, 13, 17,
	30, 34, 36, 40, 18, 24, -46, -47, 14, -44,
	-51, -52, -53, -45, 5, 7, 27, 28, 13, 29,
	14, 25, 37, 46, 38, -8, -54, -6, -42, -16,
	-17, -14, 24, 40, 34, -41, -48, -43, -49, 9,
	14, 17, 29, 30, -9, 36, 13, -24, -3, -31,
	14, -17, 9, -27, -14, -33, 14, 29, -17, 9,
	-13, -13, -27, -13, -14, -41, 14, -14, -8, -4,
	-6, -13, -14, -4, -8, -29, -6, -36, 13, -38,
	40, -10, -10, -11, 34, -8, -37, 29, -47, -45,
	46, -23, 13, 16, -13, -14, 46, -13, -43, -49,
	-12, 44, 6, 34, 46, -14, -13, -13, -13, -14,
	-18, -13, -19, -13, -14, -14, -28, -33, -17, -41,
	17, -33, -17, -13, -13, -10, -11, -8, -13, -13,
	-6, 31, -34, -33, -11, -53, -51, -52, -23, -14,
	-13, 34, -41, 46, 46, 13, -18, -13, -14, -17,
	-17, -13, -14, -27, -13, -17, -13, -16, -13, -15,
	-16, -13, -41, -36, -11, -28, -8, 46, 46, -13,
	13, 13, 46, -17, -27, -13, -17, -17, -13, -27,
	-8, -14, -13, -16, -14, -13, -16, -17, -14, -11,
	46, 46, 13, -13, -27, -14, -13, -29, -36, -13,
	-14, -14, -13, -14, -14, -33, 46, -17, -13, -17,
	-14, -8, -17, -17, -17, -17, -17, -17, -13, -17,
	-17, -28, -14, -29, -8, -11, -17,
}

var yyDef = [...]int16{
	0, -2, 1, 0, 15, 0, 119, 0, 0, 42,
	0, 4, 46, 0, 94, 79, 35, 152, -2, 130,
	0, 0, 84, 65, 0, 174, 162, 116, 37, 164,
	165, 106, 67, 68, 175, 127, 157, 177, -2, -2,
	129, 131, 132, 2, 8, 10, 11, 12, 0, 38,
	40, 41, 3, 4, 16, 35, 18, 0, 42, 120,
	144, 19, 45, 0, 71, 44, 0, 73, 74, 75,
	76, 77, 78, 0, 0, 0, 0, 71, 47, 65,
	119, 0, 0, 0, 85, 99, 0, 0, 98, -2,
	103, 104, 105, 101, 94, 0, 169, 87, 89, 90,
	91, 92, 93, 181, 179, 180, 153, 154, 156, 145,
	167, 168, 0, 146, 184, 185, 186, 187, 182, 150,
	148, 149, 151, 13, 0, 166, 175, 114, 127, 0,
	116, 119, 133, 134, 0, 0, 158, 137, 159, 139,
	-2, 141, 142, 143, 107, 0, 178, 9, 17, 39,
	41, 20, 0, 71, 0, 0, 161, 150, 22, 0,
	0, 0, 72, 124, 125, 0, 140, 0, -2, 51,
	79, 0, 0, 50, 94, 0, 82, 86, 89, 95,
	100, 0, 97, -2, 102, 94, 88, 183, 155, 147,
	170, 6, 14, 13, 0, 0, 0, 117, 138, 160,
	108, 111, 0, 0, 0, 0, 0, 32, 52, 0,
	0, 42, 43, 0, 0, 53, 0, 162, 121, 136,
	-2, 162, 122, 115, 126, -2, 162, 94, 124, 135,
	83, 96, 0, 70, 81, 0, 172, 173, 7, 125,
	124, 0, 0, 0, 0, 0, 0, 0, 0, 33,
	54, 0, 0, 0, 0, 55, 0, 0, 162, 163,
	0, 162, 0, 162, 80, 0, 94, 171, 109, 118,
	0, 0, 0, 21, 0, 0, 56, 23, 0, 0,
	85, 0, 0, 0, 0, 0, 0, 123, 0, 64,
	112, 113, 0, 24, 0, 25, 0, 0, 86, 0,
	0, 0, 0, 0, 0, 0, 110, 28, 26, 29,
	27, 34, 57, 58, 59, 60, 61, 62, 135, 30,
	31, 0, 85, 0, 94, 0, 63,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTimeRanges = yyDollar[1].DateTimeRanges
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = yyDollar[1].DateTimeRanges
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = yyDollar[2].DateTimeRanges
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTimeRanges = &DateTimeRanges{Items: []*DateTimeRange{yyDollar[1].DateTimeRange}}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = yyDollar[2].DateTimeRanges
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRanges = AppendDateTimeRanges(yyDollar[1].DateTimeRanges, yyDollar[3].DateTimeRange)
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(NewMDsYDates(yyDollar[1].string, yyDollar[2].strings, nil)...)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(NewDsMYDates(yyDollar[1].strings, yyDollar[2].string, nil)...)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(NewMDsYDates(yyDollar[1].string, yyDollar[2].strings, yyDollar[3].string)...)
		}
	case 21:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(append(NewMDsYDates(yyDollar[1].string, yyDollar[2].strings, yyDollar[6].string), NewMDsYDates(yyDollar[4].string, yyDollar[5].strings, yyDollar[6].string)...)...)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(NewDsMYDates(yyDollar[1].strings, yyDollar[2].string, yyDollar[3].string)...)
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRangesWithStartDates(append(NewDsMYDates(yyDollar[1].strings, yyDollar[2].string, yyDollar[6].string), NewDsMYDates(yyDollar[4].strings, yyDollar[5].string, yyDollar[6].string)...)...)
		}
	case 24:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[2].string, nil), NewMDYDate(yyDollar[1].string, yyDollar[4].string, nil)), NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[5].string, nil), NewMDYDate(yyDollar[1].string, yyDollar[7].string, nil)))
		}
	case 25:
		yyDollar = yyS[yypt-7 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewDMYDate(yyDollar[1].string, yyDollar[7].string, nil), NewDMYDate(yyDollar[3].string, yyDollar[7].string, nil)), NewRangeWithStartEndDates(NewDMYDate(yyDollar[4].string, yyDollar[7].string, nil), NewDMYDate(yyDollar[6].string, yyDollar[7].string, nil)))
		}
	case 26:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[2].string, nil), NewMDYDate(yyDollar[1].string, yyDollar[4].string, nil)), NewRangeWithStartEndDates(NewMDYDate(yyDollar[5].string, yyDollar[6].string, nil), NewMDYDate(yyDollar[5].string, yyDollar[8].string, nil)))
		}
	case 27:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewDMYDate(yyDollar[1].string, yyDollar[4].string, nil), NewDMYDate(yyDollar[3].string, yyDollar[4].string, nil)), NewRangeWithStartEndDates(NewDMYDate(yyDollar[5].string, yyDollar[8].string, nil), NewDMYDate(yyDollar[7].string, yyDollar[8].string, nil)))
		}
	case 28:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[8].string), NewMDYDate(yyDollar[1].string, yyDollar[4].string, yyDollar[8].string)), NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[5].string, yyDollar[8].string), NewMDYDate(yyDollar[1].string, yyDollar[7].string, yyDollar[8].string)))
		}
	case 29:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewDMYDate(yyDollar[1].string, yyDollar[7].string, yyDollar[8].string), NewDMYDate(yyDollar[3].string, yyDollar[7].string, yyDollar[8].string)), NewRangeWithStartEndDates(NewDMYDate(yyDollar[4].string, yyDollar[7].string, yyDollar[8].string), NewDMYDate(yyDollar[6].string, yyDollar[7].string, yyDollar[8].string)))
		}
	case 30:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[9].string), NewMDYDate(yyDollar[1].string, yyDollar[4].string, yyDollar[9].string)), NewRangeWithStartEndDates(NewMDYDate(yyDollar[5].string, yyDollar[6].string, yyDollar[9].string), NewMDYDate(yyDollar[5].string, yyDollar[8].string, yyDollar[9].string)))
		}
	case 31:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStartEndDates(NewDMYDate(yyDollar[1].string, yyDollar[4].string, yyDollar[9].string), NewDMYDate(yyDollar[3].string, yyDollar[4].string, yyDollar[9].string)), NewRangeWithStartEndDates(NewDMYDate(yyDollar[5].string, yyDollar[8].string, yyDollar[9].string), NewDMYDate(yyDollar[7].string, yyDollar[8].string, yyDollar[9].string)))
		}
	case 32:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStart(NewMDYDate(yyDollar[1].string, yyDollar[2].string, nil)), NewRangeWithStart(NewMDYDate(yyDollar[3].string, yyDollar[4].string, nil)))
		}
	case 33:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRangeWithStart(NewMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string)), NewRangeWithStart(NewMDYDate(yyDollar[3].string, yyDollar[4].string, yyDollar[5].string)))
		}
	case 34:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRanges = NewRanges(NewRange(NewDateTime(NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil), yyDollar[6].Time, nil), NewDateTime(NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil), yyDollar[8].Time, nil)), NewRange(NewDateTime(NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[6].Time, nil), NewDateTime(NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string, nil), yyDollar[8].Time, nil)))
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strings = []string{yyDollar[1].string}
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.strings = []string{yyDollar[1].string, yyDollar[2].string}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.strings = append(yyDollar[1].strings, yyDollar[2].string)
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTimeRange = &DateTimeRange{Start: yyDollar[1].DateTime}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTimeRange = yyDollar[2].DateTimeRange
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(yyDollar[1].DateTime, NewDateTime(yyDollar[1].DateTime.Date, yyDollar[3].Time, yyDollar[1].DateTime.TimeZone))
		}
	case 49:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(yyDollar[1].DateTime.Date, yyDollar[1].DateTime.Time, yyDollar[4].TimeZone), NewDateTime(yyDollar[1].DateTime.Date, yyDollar[3].Time, yyDollar[4].TimeZone))
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(yyDollar[3].DateTime.Date, yyDollar[1].Time, yyDollar[3].DateTime.TimeZone), yyDollar[3].DateTime)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTimeRange = &DateTimeRange{Start: yyDollar[1].DateTime, End: yyDollar[3].DateTime}
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[2].string, nil), NewMDYDate(yyDollar[1].string, yyDollar[4].string, nil))
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewDMYDate(yyDollar[1].string, yyDollar[4].string, nil), NewDMYDate(yyDollar[3].string, yyDollar[4].string, nil))
		}
	case 54:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[5].string), NewMDYDate(yyDollar[1].string, yyDollar[4].string, yyDollar[5].string))
		}
	case 55:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewDMYDate(yyDollar[1].string, yyDollar[4].string, yyDollar[5].string), NewDMYDate(yyDollar[3].string, yyDollar[4].string, yyDollar[5].string))
		}
	case 56:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[6].string), NewMDYDate(yyDollar[4].string, yyDollar[5].string, yyDollar[6].string))
		}
	case 57:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[8].string), NewWMDYDate(yyDollar[5].string, yyDollar[6].string, yyDollar[7].string, yyDollar[8].string))
		}
	case 58:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[8].string), NewWDMYDate(yyDollar[5].string, yyDollar[6].string, yyDollar[7].string, yyDollar[8].string))
		}
	case 59:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[8].string), NewWDMYDate(yyDollar[6].string, yyDollar[5].string, yyDollar[7].string, yyDollar[8].string))
		}
	case 60:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewWDMYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[8].string), NewWMDYDate(yyDollar[5].string, yyDollar[6].string, yyDollar[7].string, yyDollar[8].string))
		}
	case 61:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewWDMYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[8].string), NewWDMYDate(yyDollar[5].string, yyDollar[6].string, yyDollar[7].string, yyDollar[8].string))
		}
	case 62:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRangeWithStartEndDates(NewWDMYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[8].string), NewWDMYDate(yyDollar[6].string, yyDollar[5].string, yyDollar[7].string, yyDollar[8].string))
		}
	case 63:
		yyDollar = yyS[yypt-14 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(NewDMYDate(yyDollar[4].string, yyDollar[6].string, yyDollar[14].string), yyDollar[1].Time, yyDollar[2].TimeZone), NewDateTime(NewDMYDate(yyDollar[8].string, yyDollar[10].string, yyDollar[14].string), yyDollar[12].Time, yyDollar[13].TimeZone))
		}
	case 64:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.DateTimeRange = NewRange(NewDateTime(yyDollar[1].Date, yyDollar[2].Time, yyDollar[3].TimeZone), NewDateTime(yyDollar[1].Date, yyDollar[5].Time, yyDollar[6].TimeZone))
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTime = NewDateTimeWithDate(yyDollar[1].Date, nil)
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, yyDollar[2].Time, yyDollar[3].TimeZone)
		}
	case 81:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, yyDollar[3].Time, yyDollar[4].TimeZone)
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[3].Date, yyDollar[1].Time, yyDollar[2].TimeZone)
		}
	case 83:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[4].Date, yyDollar[1].Time, yyDollar[2].TimeZone)
		}
	case 94:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.TimeZone = nil
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.TimeZone = yyDollar[1].TimeZone
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.TimeZone = yyDollar[2].TimeZone
		}
	case 97:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.TimeZone = yyDollar[2].TimeZone
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = nil
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(yyDollar[1].string, nil, nil)
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(nil, yyDollar[1].string, nil)
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(nil, "P", nil)
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DateTime = NewDateTimeWithDate(yyDollar[1].Date, nil)
		}
	case 107:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, yyDollar[2].Time, nil)
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DateTime = NewDateTime(yyDollar[1].Date, yyDollar[2].Time, yyDollar[3].TimeZone)
		}
	case 109:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.Date = NewDMYDate(yyDollar[5].string, yyDollar[3].string, yyDollar[1].string)
		}
	case 110:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[2].string, yyDollar[4].string, yyDollar[6].string, nil)
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.TimeZone = nil
		}
	case 112:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(nil, nil, "+"+yyDollar[2].string+":"+yyDollar[4].string)
		}
	case 113:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.TimeZone = NewTimeZone(nil, nil, "-"+yyDollar[2].string+":"+yyDollar[4].string)
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Date = yyDollar[2].Date
		}
	case 115:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Date = NewAmbiguousDate(yyDollar[1].string, yyDollar[2].string, yyDollar[4].string, nil)
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Date = NewDMYDate(nil, nil, yyDollar[1].string)
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Date = NewDMYDate(nil, yyDollar[3].string, yyDollar[1].string)
		}
	case 118:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.Date = NewDMYDate(yyDollar[5].string, yyDollar[3].string, yyDollar[1].string)
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Date = NewMDYDate(yyDollar[1].string, nil, nil)
		}
	case 120:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Date = NewMDYDate(yyDollar[1].string, nil, yyDollar[2].string)
		}
	case 121:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Date = NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[4].string)
		}
	case 122:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Date = NewWDMYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, yyDollar[4].string)
		}
	case 123:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Date = NewAmbiguousDate(yyDollar[1].string, yyDollar[2].string, yyDollar[4].string, yyDollar[6].string)
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Date = NewWMDYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil)
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Date = NewWDMYDate(yyDollar[1].string, yyDollar[2].string, yyDollar[3].string, nil)
		}
	case 126:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Date = NewWDMYDate(yyDollar[1].string, yyDollar[4].string, yyDollar[3].string, yyDollar[2].string)
		}
	case 162:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.string = ""
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.string = "TH"
		}
	case 166:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Time = yyDollar[2].Time
		}
	case 167:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Time = NewAMTime(yyDollar[1].string, nil, nil, nil)
		}
	case 168:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Time = NewPMTime(yyDollar[1].string, nil, nil, nil)
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[1].string, nil, nil, nil)
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[1].string, yyDollar[3].string, nil, nil)
		}
	case 171:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[1].string, yyDollar[3].string, yyDollar[5].string, nil)
		}
	case 172:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Time = NewAMTime(yyDollar[1].string, yyDollar[3].string, nil, nil)
		}
	case 173:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.Time = NewPMTime(yyDollar[1].string, yyDollar[3].string, nil, nil)
		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Time = NewTime(yyDollar[1].string, nil, nil, nil)
		}
	}
	goto yystack /* stack new state and value */
}
