package datetime

import (
	"errors"
	"html"
	"regexp"
	"strconv"
	"strings"
	"time"

	"go/scanner"
	"go/token"

	"github.com/findyourpaths/phil/glr"
	"github.com/microcosm-cc/bluemonday"
)

// datetimeLexer implements yyLexer interface for the parser generated by goyacc,
// and also GLR's Lexer interface.
type datetimeLexer struct {
	lval       *yySymType
	scanner    scanner.Scanner
	err        error
	root       *DateTimeRanges
	recurrence *Recurrence // captured from stripped plural weekday prefix
}

// Match a digit on one side and a letter on another. Used to separate `12pm`.
var boundaryRE1 = regexp.MustCompile(`([[:alpha:]])([[:^alpha:]])`)
var boundaryRE2 = regexp.MustCompile(`([[:^alpha:]])([[:alpha:]])`)

// var spacifyRE = regexp.MustCompile(`\s*\b(.|-)\b\s*`)
var spacifyRE = regexp.MustCompile(`(?:^|\s*\b)(.|-)(?:\b\s*|$)`)

// ianaTimezoneRE matches IANA timezone paths like "US/Eastern", "America/New_York".
var ianaTimezoneRE = regexp.MustCompile(`[A-Z][a-zA-Z_]+/[A-Z][a-zA-Z_]+`)

// dayNumberRE matches "Day N" session numbering (e.g. "Day 1", "Day 2") that interferes
// with date parsing when the number gets consumed as a Time (hour).
var dayNumberRE = regexp.MustCompile(`(?i)\bday\s+\d\b`)

// markdownBoldRE matches markdown bold formatting (**...**) which often contains
// title text with tokens like "and", ":", "+" that interfere with date parsing.
var markdownBoldRE = regexp.MustCompile(`\*\*[^*]+\*\*`)

// weekdayCountRE matches a leading digit count before a weekday name (e.g. "2 Wednesdays",
// "5 Tuesdays"). The count gets misinterpreted as a Time (hour) by the parser.
// Stripping it preserves the weekday while removing the ambiguous number.
var weekdayCountRE = regexp.MustCompile(`(?i)\b\d+\s+((?:mon|tue|wed|thu|fri|sat|sun)\w*)`)

// weekdayPluralPrefixRE matches a leading PLURAL weekday name followed by a separator
// (comma, dash, colon), "at", or just whitespace (for "Tuesdays 7 to 9 pm" where no
// separator exists between weekday and time). The plural weekday is informational and
// interferes with parsing when left in. Only strips plural forms (ending in "s") to
// preserve singular weekdays needed for disambiguation.
// Allows leading whitespace for cases where a noise word (e.g. "NEW") was already stripped.
var weekdayPluralPrefixRE = regexp.MustCompile(`(?i)^\s*(?:mondays|tuesdays|wednesdays|thursdays|fridays|saturdays|sundays)(?:\s*[-,:]|\s+at\b|\s+)`)

// everyWeekdayRE matches "every WEEKDAY" (with optional "other" modifier) anywhere in the
// input. In "every Wednesday from 9 - 12 pm beginning February 1st", the "every Wednesday"
// is recurrence metadata. Stripping it leaves the time range + date which parses normally.
// Captures the weekday name in group 1 for recurrence extraction.
var everyWeekdayRE = regexp.MustCompile(`(?i)\bevery\s+(?:other\s+)?((?:mon|tue|wed|thu|fri|sat|sun)\w*)\b`)

// weekdaySingularTimeRangeRE matches a singular weekday (with optional slash-separated
// alternatives) at the start of input, followed by a time RANGE pattern: digit +
// am/pm/colon, then a range separator (to, -, –, through, till, until), then another
// digit. In "Sat 5pm to 2am", the weekday is informational and prevents the parser from
// forming a time-only range. Only strips when a range separator is present to avoid
// stripping weekdays in "Sunday 1:30 PM" (single time with meaningful weekday for
// minDT date resolution).
var weekdaySingularTimeRangeRE = regexp.MustCompile(`(?i)^(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday|mon|tue|wed|thu|fri|sat|sun)(?:\s*/\s*(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday|mon|tue|wed|thu|fri|sat|sun))*\s+(\d+\s*(?:am|pm|:\d).*(?:\bto\b|\btill\b|\bthrough\b|\buntil\b|-|–).*\d.*)$`)

// dayRangeBeforeMonthRE matches a small day range like "1-3" immediately before a month
// name (with optional separator). Expands "1-3 Feb" → "1, 2, 3 Feb" so the existing
// DayPlus1 grammar rules handle the list. The month lookahead ensures we don't expand
// time ranges or cross-month date ranges like "Feb 3 - Mar 2".
var dayRangeBeforeMonthRE = regexp.MustCompile(`(?i)\b(\d{1,2})\s*-\s*(\d{1,2})\s*([&,]?\s*(?:` +
	`jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\w*)`)

// dayRangeBeforeSepRE matches "1-3 &" or "1-3 and" — day range before another day list
// segment. Expands "1-3 & 5" → "1, 2, 3 & 5".
var dayRangeBeforeSepRE = regexp.MustCompile(`(?i)\b(\d{1,2})\s*-\s*(\d{1,2})\s*(&|\band\b)`)

// circaRE matches "ca." (German abbreviation for "circa") followed by a digit.
// Without stripping, "ca.12" becomes ".12" (FLOAT token) after boundary splitting,
// which prevents the "12" from being parsed as INT for time.
var circaRE = regexp.MustCompile(`(?i)\bca\.(\d)`)

// redundantTimeRE matches a 12-hour time (H:MM AM/PM) immediately followed by
// a redundant 24-hour time (HH:MM). Common in Google Calendar ICS exports.
// Example: "3:00 PM 15:00" → collapseRedundantTimes strips the "15:00".
var redundantTimeRE = regexp.MustCompile(`(?i)(\d{1,2}:\d{2}\s+[AP]M)\s+(\d{1,2}:\d{2})`)

// noiseLabelRE matches labels that precede dates/times in event listings.
// The colon would be consumed as a DatePrefix by the parser, and the label
// words become IDENT tokens that confuse the GLR parser's scoring.
// Examples: "Doors: 8PM", "Show: 9PM", "Course Schedule: 1, 3 Feb 2023"
var noiseLabelRE = regexp.MustCompile(`(?i)\b(?:doors|show|course\s+schedule|schedule)\s*:`)

// noiseAgePlusRE matches age restrictions like "21+" with optional suffix text
// (e.g. "21+RSVP DOES NOT GUARANTEE ENTRY") up to the next "/" or end of string.
var noiseAgePlusRE = regexp.MustCompile(`21\+[^/]*`)

// noiseFreeRE matches standalone "Free" price indicator.
var noiseFreeRE = regexp.MustCompile(`(?i)\bfree\b`)

// noiseSessionsRE matches parenthesized session counts like "(4 sessions)" or "(45 sessions)".
var noiseSessionsRE = regexp.MustCompile(`(?i)\(\s*\d+\s+sessions?\s*\)`)

// noiseNewRE matches "NEW" at the start of an input (event title marker).
// Case-sensitive uppercase only to avoid stripping "New" in "New York" etc.
var noiseNewRE = regexp.MustCompile(`^\s*NEW\b`)

// commaBeforeAndRE strips commas before "and" in day lists like "30 March, and 1 April".
// The comma is consumed as RangesSep by the grammar, breaking the DayPlus Month AND
// DayPlus Month pattern. Without this, "30 March, and" splits at the comma.
var commaBeforeAndRE = regexp.MustCompile(`(?i),\s+and\b`)

// multiMonthCommaRE normalizes "30 June, 2 July" to "30 June and 2 July" by replacing
// the comma between Month and Day-Month with " and". Without "and", the grammar has no
// rule to bind both months to a shared trailing Year, so the first month's items get year=0.
// Matches DM order only: "Day(s) Month, Day(s) Month" where Month is a full or abbreviated name.
var multiMonthCommaRE = regexp.MustCompile(`(?i)(` + monthNamesRE + `)\s*,\s*(\d{1,2}\s+` + monthNamesRE + `)`)

// monthNamesRE matches English month names (full and 3-letter abbreviations).
const monthNamesRE = `(?:jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|june?|july?|aug(?:ust)?|sept?(?:ember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)`

// extraTimezoneBlockRE strips alternate timezone displays after the first
// parenthesized timezone abbreviation. Common in multi-timezone listings like:
//
//	"17:00 – 21:00 (SAST) 08:00 – 12:00 (PDT)"
//	"07:00 AM – 11:00 AM (SAST) 09:00 AM – 13:00 PM (GMT+4) DUBAI ..."
//
// Keeps the first "(TZ)" and discards everything after it when followed by
// a time-range pattern (indicating alternate timezone displays).
var extraTimezoneBlockRE = regexp.MustCompile(`(?i)(\([A-Z]{2,5}\))\s+\d{1,2}:\s*\d{2}\s*(?:[AP]M\s*)?[–\-].*`)

// brokenTimeColonRE collapses stray spaces in time patterns like "07: 00" → "07:00".
// Common artifact from HTML strip_tags + collapse_spaces where "07:<br>00" or
// "07:</span> <span>00" becomes "07: 00". Only matches when exactly 2 digits
// follow the colon (minutes), avoiding date-time separators like "3: 9am".
var brokenTimeColonRE = regexp.MustCompile(`\b(\d{1,2}):\s+(\d{2})\b`)

// colonDateTimeSepRE converts a colon between a day number and a time into a comma.
// In "February 3: 9am", the colon is a presentational separator, not a time separator.
// Without this, "3:9" gets consumed as Time(3:09). Requires whitespace after the colon
// to avoid matching legitimate times like "3:30pm".
var colonDateTimeSepRE = regexp.MustCompile(`(?i)(\d)\s*:\s+(\d+\s*(?:am|pm))`)

// slashTimesSepRE converts "/" between AM/PM times to "," so the grammar's
// RangesSep (which includes COMMA but not QUO) can separate them.
// Matches "PM / 9" or "AM / 12" patterns. Does not match "2/3" date separators.
var slashTimesSepRE = regexp.MustCompile(`(?i)([AP]M)\s*/\s*(\d)`)

// twoDigitYearRE matches M/D/YY or D/M/YY patterns where the year is exactly 2 digits.
// The negative lookahead (?!\d) prevents matching 4-digit years like "2/3/2023".
var twoDigitYearRE = regexp.MustCompile(`(\d{1,2}/\d{1,2}/)(\d{2})(?:\D|$)`)

// expandTwoDigitYears replaces 2-digit years in slash-separated date patterns
// with 4-digit years (00-49 → 2000s, 50-99 → 1900s) before boundary splitting
// would separate the components.
// expandDayRange replaces a day range "N-M" with "N, N+1, ..., M" when followed
// by a month name or "&"/"and" separator. Only expands when both N and M are valid
// days (1-31) and N < M.
func expandDayRange(input string) string {
	expand := func(re *regexp.Regexp, input string) string {
		return re.ReplaceAllStringFunc(input, func(match string) string {
			sub := re.FindStringSubmatch(match)
			start, _ := strconv.Atoi(sub[1])
			end, _ := strconv.Atoi(sub[2])
			if start < 1 || end > 31 || start >= end || end-start > 10 || end-start < 2 {
				return match // not a valid day range or only 2 adjacent days (grammar handles those)
			}
			days := make([]string, 0, end-start+1)
			for d := start; d <= end; d++ {
				days = append(days, strconv.Itoa(d))
			}
			// sub[3] is the trailing context (month name or separator) — preserve it
			return strings.Join(days, ", ") + " " + sub[3]
		})
	}
	input = expand(dayRangeBeforeMonthRE, input)
	input = expand(dayRangeBeforeSepRE, input)
	return input
}

func expandTwoDigitYears(input string) string {
	return twoDigitYearRE.ReplaceAllStringFunc(input, func(match string) string {
		sub := twoDigitYearRE.FindStringSubmatch(match)
		yy, _ := strconv.Atoi(sub[2])
		if yy < 50 {
			yy += 2000
		} else {
			yy += 1900
		}
		// Preserve the trailing non-digit character
		trail := match[len(sub[1])+len(sub[2]):]
		return sub[1] + strconv.Itoa(yy) + trail
	})
}

// replaceIANATimezones replaces IANA timezone paths with their standard abbreviation
// before input preprocessing splits them at the "/".
func replaceIANATimezones(input string) string {
	return ianaTimezoneRE.ReplaceAllStringFunc(input, func(match string) string {
		if tz, _ := timezoneTZ.GetTzInfo(match); tz != nil {
			return tz.ShortGeneric()
		}
		return match
	})
}

// collapseRedundantTimes removes redundant 24-hour times that immediately follow
// their 12-hour equivalents. Common in Google Calendar ICS exports where times
// appear as "3:00 PM 15:00". Only strips when the 24h time matches the 12h time.
func collapseRedundantTimes(input string) string {
	return redundantTimeRE.ReplaceAllStringFunc(input, func(match string) string {
		sub := redundantTimeRE.FindStringSubmatch(match)
		// Parse 12h components: "3:00 PM" → hour=3, min=0, ampm="PM"
		parts := strings.FieldsFunc(sub[1], func(r rune) bool { return r == ':' || r == ' ' })
		h12, _ := strconv.Atoi(parts[0])
		m12, _ := strconv.Atoi(parts[1])
		ampm := strings.ToUpper(parts[2])

		// Convert to expected 24h value
		h24 := h12
		if ampm == "PM" && h12 != 12 {
			h24 += 12
		} else if ampm == "AM" && h12 == 12 {
			h24 = 0
		}

		// Parse actual 24h components: "15:00" → hour=15, min=0
		parts24 := strings.Split(sub[2], ":")
		h24Actual, _ := strconv.Atoi(parts24[0])
		m24Actual, _ := strconv.Atoi(parts24[1])

		if h24 == h24Actual && m12 == m24Actual {
			return sub[1] // Strip redundant 24h time
		}
		return match // Keep both if they don't match
	})
}

// noisePatterns are stripped with empty replacement during preprocessing.
var noisePatterns = []*regexp.Regexp{
	noiseNewRE, noiseLabelRE, noiseAgePlusRE, noiseFreeRE, noiseSessionsRE,
}

// stripPatterns are applied with specific replacements during preprocessing.
var stripPatterns = []struct {
	re   *regexp.Regexp
	repl string
}{
	{weekdayCountRE, "$1"},
	{weekdayPluralPrefixRE, ""},
	{everyWeekdayRE, ""},
	{weekdaySingularTimeRangeRE, "$1"},
	{dayNumberRE, ""},
	{markdownBoldRE, ""},
	{circaRE, "$1"},
}

// preprocessResult holds the cleaned input and any metadata extracted during preprocessing.
type preprocessResult struct {
	input      string
	recurrence *Recurrence
}

// preprocess normalizes the input string and extracts recurrence metadata.
// This is a pure function: input string in, result struct out.
func preprocess(input string) preprocessResult {
	debugf("in before processing: %q\n", input)

	// Normalization: timezone paths, 2-digit years, day ranges.
	input = replaceIANATimezones(input)
	input = expandTwoDigitYears(input)
	input = expandDayRange(input)

	// Noise stripping.
	for _, re := range noisePatterns {
		input = re.ReplaceAllString(input, "")
	}

	// Capture recurrence weekday from plural prefix or "every WEEKDAY" before stripping.
	var recurrence *Recurrence
	if m := weekdayPluralPrefixRE.FindString(input); m != "" {
		wdName := strings.ToLower(strings.TrimRight(strings.Fields(m)[0], "s"))
		if wd, ok := weekdaysByNames[wdName]; ok {
			recurrence = &Recurrence{Frequency: FrequencyWeekly, Weekdays: []time.Weekday{wd}}
		}
	} else if sub := everyWeekdayRE.FindStringSubmatch(input); sub != nil {
		wdName := strings.ToLower(strings.TrimSuffix(sub[1], "s"))
		if wd, ok := weekdaysByNames[wdName]; ok {
			recurrence = &Recurrence{Frequency: FrequencyWeekly, Weekdays: []time.Weekday{wd}}
		}
	}

	// Strip patterns (weekday counts, plural prefixes, etc.).
	for _, sp := range stripPatterns {
		input = sp.re.ReplaceAllString(input, sp.repl)
	}

	// Collapse redundant 24h times after their 12h equivalents (Google Calendar ICS).
	input = collapseRedundantTimes(input)

	// Strip extra timezone blocks (keep only first). Apply repeatedly for 3+ TZ blocks.
	for extraTimezoneBlockRE.MatchString(input) {
		input = extraTimezoneBlockRE.ReplaceAllString(input, "$1")
	}

	// Normalize comma-before-and to just "and" for day list grammar.
	input = commaBeforeAndRE.ReplaceAllString(input, " and")

	// Normalize multi-month comma to "and": "30 June, 2 July" → "30 June and 2 July".
	// Must run after commaBeforeAndRE (which handles ", and" → " and").
	input = multiMonthCommaRE.ReplaceAllString(input, "$1 and $2")

	// Separator conversion: broken time colons.
	input = brokenTimeColonRE.ReplaceAllString(input, "$1:$2")

	// Separator conversions.
	input = colonDateTimeSepRE.ReplaceAllString(input, "$1, $2")
	input = slashTimesSepRE.ReplaceAllString(input, "$1, $2")

	// Boundary splitting and final cleanup.
	input = boundaryRE1.ReplaceAllString(input, `$1 $2`)
	input = boundaryRE2.ReplaceAllString(input, `$1 $2`)
	input = spacifyRE.ReplaceAllString(input, ` $1 `)
	input = strings.Replace(input, " ' ", " ", -1)
	input = CleanTextLine(input)
	debugf("input after processing: %q\n", input)

	return preprocessResult{input: input, recurrence: recurrence}
}

func NewDatetimeLexer(input string) *datetimeLexer {
	pp := preprocess(input)
	l := &datetimeLexer{
		lval:       &yySymType{},
		recurrence: pp.recurrence,
	}
	l.scanner = glr.NewLexerScanner(l, pp.input)
	return l
}

var whitespacesRE = regexp.MustCompile(`\s+`)

func CleanTextLine(s string) string {
	r := bluemonday.StrictPolicy().AddSpaceWhenStrippingTag(true).Sanitize(s)
	r = html.UnescapeString(r)
	r = strings.ReplaceAll(r, "\u00a0", " ")
	r = whitespacesRE.ReplaceAllString(r, " ")
	r = strings.TrimSpace(r)
	return r
}

func (l *datetimeLexer) NextToken(pos int) (string, string, bool) {
	val := l.Lex(l.lval)
	sym := l.lval.string
	if val >= 57343 {
		sym = yyToknames[val-57343]
	}
	// fmt.Printf("sym: %q, l.lval.string: %q, val: %d\n", sym, l.lval.string, val)
	return sym, l.lval.string, val >= 0
}

func (l *datetimeLexer) Error(msg string) {
	l.err = errors.New(msg)
}

// yySymType is generated by goyacc
func (l *datetimeLexer) Lex(lval *yySymType) int {
	for {
		_, tok, lit := l.scanner.Scan()
		features := ""
		if tok == token.ILLEGAL {
			features += " ILLEGAL"
		}
		if tok == token.IDENT {
			features += " IDENT"
		}
		debugf("scanned literal: %q as token: %q%s\n", lit, tok, features)

		// Skip whitespace and semicolons
		if tok == token.SEMICOLON {
			continue
		}
		if tok == token.EOF {
			lval.string = "$end"
			return -1
		}

		lval.string = lit
		if lit == "" {
			lval.string = tok.String()
		}
		// fmt.Printf("lval.string: %#v\n", lval.string)

		switch tok {

		case token.ILLEGAL:
			litl := strings.ToLower(lit)
			switch litl {
			case "@":
				return AMP

			case "–":
				return SUB

			case "—":
				return SUB

			case "•":
				return BULLET

			case "·":
				return COMMA

			default:
				return ILLEGAL
			}

		case token.IDENT:
			lowLit := strings.ToLower(lit)
			switch lowLit {
			case "a":
				return A
			case "am":
				return AM
			case "and":
				return AND
			case "at":
				return AT
			case "beginning":
				return BEGINNING
			case "calendar":
				return CALENDAR
			// "date" treated as IDENT to avoid "Day 2" being consumed as DATE
			// token (DatePrefix) which kills parser branches that could skip it
			// as noise. "Date:" tests still work because COLON alone is DatePrefix.
			// case "date":
			// 	return DATE
			case "dates":
				return DATES
			case "from":
				return FROM
			case "google":
				return GOOGLE
			case "ics":
				return ICS
			case "in":
				return IN
			case "midnight":
				return TIME_NAME
			// "next" treated as IDENT to avoid consuming it as WeekdayPrefix
			// when it appears as noise in sentences (e.g. "Our next cohort...").
			// The WeekdayPrefix grammar rule discards the prefix anyway.
			// case "next":
			// 	return NEXT
			case "noon":
				return TIME_NAME
			case "of":
				return OF
			case "on":
				return ON
			case "part":
				return PART
			case "p":
				return P
			case "pm":
				return PM
			case "save":
				return SAVE
			case "start", "starts":
				return STARTS
			case "end", "ends":
				return ENDS
			case "through":
				return THROUGH
			case "t":
				return T
			case "th":
				return TH
			case "the":
				return THE
			case "till":
				return TILL
			case "this":
				return THIS
			case "time":
				return TIME
			case "to":
				return TO
			case "today":
				return RELATIVE_DAY
			case "tomorrow":
				return RELATIVE_DAY
			case "until":
				return UNTIL
			case "when":
				return WHEN
			case "yesterday":
				return RELATIVE_DAY
			case "z":
				return Z

			default:
				if ordinals[lowLit] {
					return ORD_IND
				}

				if _, found := monthsByNames[lowLit]; found {
					return MONTH_NAME
				}

				if _, found := weekdaysByNames[lowLit]; found {
					if len(lowLit) < 4 {
						return WEEKDAY_SHORT_NAME
					}
					return WEEKDAY_NAME
				}

				if _, found := timeZoneAbbreviationsByNames[lowLit]; found {
					return TIME_ZONE
				}

				upLit := strings.ToUpper(lit)
				// tz, err := tzTimezone.GetTzAbbreviationInfo(upLit)
				// fmt.Println("upLit", upLit, "tz", tz, "err", err)
				// Ignore single-char timezone abbreviations - too many false positives (e.g., "S" from "Maggiano's")
				if len(upLit) > 1 {
					if tz, _ := timezoneTZ.GetTzAbbreviationInfo(upLit); tz != nil {
						return TIME_ZONE_ABBREV
					}
				}
				if tz, _ := timezoneTZ.GetTzInfo(upLit); tz != nil {
					return TIME_ZONE
				}

				return IDENT
			}

		case token.INT:
			if len(lit) == 4 &&
				(strings.HasPrefix(lit, "17") ||
					strings.HasPrefix(lit, "18") ||
					strings.HasPrefix(lit, "19") ||
					strings.HasPrefix(lit, "20") ||
					strings.HasPrefix(lit, "21")) {
				return YEAR
			}
			return INT

		case token.ADD:
			return ADD
		case token.AND:
			return AND
		case token.COLON:
			return COLON
		case token.COMMA:
			return COMMA
		case token.DEC:
			return DEC
		case token.LPAREN:
			return LPAREN
		case token.PERIOD:
			return PERIOD
		case token.QUO:
			return QUO
		case token.RPAREN:
			return RPAREN
		case token.SEMICOLON:
			return SEMICOLON
		case token.SUB:
			return SUB
		default:
			return ILLEGAL
		}
	}
}
